### PR TITLE
Fix tests failures

### PR DESCRIPTION
**Pull request by michaelkl**
**Checklist**

- [x] I have read the [Contribution & Best practices Guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md).
- [x] My branch is up-to-date with the upstream `master` branch.
- [x] The tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works(if appropriate).
- [ ] I have added necessary documentation (if appropriate).

**Short description of what this resolves/which [issues](https://github.com/openSUSE/osem/issues) does this fix?:**

- Fix some tests failures

**Changes proposed in this pull request:**

- Fix test failures in some timezones.
- Fix test failures caused by logging changes of `updated_at` attribute.
- Fix test failures caused by hardcoded roles order.

### CODE REVIEW

**Comment by michaelkl** [comment]
@bear454 Tests fixes extracted from #2012

**Comment by bear454** [comment]
Hmm... While I don't have any objections to the changes... I wonder how you're testing, as the suite passes on TravisCI (most of the time ;-).

**Comment by michaelkl** [comment]
My timezone is UTC+5. I'm running the project with PostgreSQL as a database (because I have it locally for other projects and I was too lazy to setup MariaDB for a single project :-) ). I've also tried sqlite with exactly the same result.
I guess something breaks when we save timezone-unaware values to database and extract them later as `ActiveSupport::TimeWithZone`.

**Comment by bear454** [comment]
I'm running `osem` on Postgres as well, in UTC+~~8~~7 (P**DS**T - I _hate_ daylight savings, but that's another rant), on Ruby 2.4.1 - https://lfnw.org

**Comment by michaelkl** [comment]
I'm on Ruby 2.3.5.
[Example of failures I get](https://gist.github.com/michaelkl/a5181e00b21b2261d5b119948774bfcd)

**Comment by bear454** [comment]
Okay, so it must be a ruby-2.3 thing. Since the tests still pass on 2.4, I don't see any reason not to approve.

**Pull request merged**
