### PR TITLE
Rename 'ConferenceController' to 'ConferencesController', and 'ProposalController' to 'ProposalsController'

### PR DESCRIPTION
**Pull request by richiethomas**
https://github.com/openSUSE/osem/issues/1120

### CODE REVIEW

**Comment by differentreality** [comment]
What about 
https://github.com/openSUSE/osem/blob/master/app/views/admin/events/edit.html.haml#L1

**Comment by differentreality** [comment]
Good job switching this to its own branch! :)

**Comment by richiethomas** [comment]
Fixed "edit.html.haml".  Also found and fixed 2 references to "/proposal/" in application_helper.rb; they were just comments but it can't hurt to fix them anyway. :-)

**Comment by differentreality** [comment]
OK le'ts merge this!

**Pull request merged**
