### PR TITLE
Upgraded Rails to 4.2, and rest of gems except rubocop.

### PR DESCRIPTION
**Pull request by raluka**
Update guide from here: http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-1-to-rails-4-2.
Rails release notes: http://edgeguides.rubyonrails.org/4_2_release_notes.html
I have a failed `rubocop` test, that can be fixed by upgrading `rubocop` gem

### CODE REVIEW

**Comment by raluka** [comment]
@ChrisBr , please check this solution.

**Comment by raluka** [comment]
@hennevogel , @differentreality

**Comment by differentreality** [comment]
Not sure why rubocop complains... That's the only thing failing currently in Travis.

@raluka are you going to continue this PR?  It needs to be rebased against our current master.
@hennevogel could you review the configuration changes made?

**Comment by raluka** [comment]
Hello,
I waited for review. I'll rebase it and continue, of course.

On Thu, 14 Jan 2016 12:42 Stella Rouzi <notifications@github.com> wrote:

> Not sure why rubocop complains... That's the only thing failing currently
> in Travis.
>
> @raluka <https://github.com/raluka> are you going to continue this PR? It
> needs to be rebased against our current master.
> @hennevogel <https://github.com/hennevogel> could you review the
> configuration changes made?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openSUSE/osem/pull/732#issuecomment-171620910>.
>
-- 

--
Sent from mobile, please ignore typos

**Comment by differentreality** [comment]
@raluka please rebase after the recent changes made and let's see if we can merge this soon.

**Comment by raluka** [comment]
@differentreality done

**Comment by differentreality** [comment]
Looks like travis did not run on this PR for some reason. Weird.

**Comment by hennevogel** [comment]
The rails update happened in another commit now 9e9c53694655f28fb8e7fc4eda426f55c09602b3

thanks for your work anyway @raluka :-)

**Pull request closed without merging**
