### PR TITLE
Few things I stumbled over while waiting for tests to finish:)

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by differentreality** [comment]
Travis failure is a styling thing from rubocop.

We should use single quotes unless we have interpolation.
So, for instance,  event.abstract = ""   should be  event.abstract = ''

**Comment by hennevogel** [comment]
Please fix the styling issues

**Comment by hennevogel** [comment]
@bgeuken whats up? :-)

**Comment by bgeuken** [comment]
Oups, almost forgot... I've updated it now.

**Comment by hennevogel** [comment]
Thank you :-) :+1:

**Pull request merged**
