### PR TITLE
Edit styling in conferences/_lodging

### PR DESCRIPTION
**Pull request by StavyVen**
Corrections in styling issues in app/views/conferences/_lodging.html.haml.

### CODE REVIEW

**Comment by differentreality** [comment]
Nice, thanks @StavyVen :)
The last commit doesn't have to be a commit on its own, can you please squash it?
Feel free to reach out if you need help squashing it.

**Comment by differentreality** [comment]
@StavyVen do you need help to proceed with the necessary changes? There seem to be some conflicts that need fixing as well.

**Comment by bear454** [comment]
Screenshots too please (for any visual change).

**Comment by Ana06** [comment]
@StavyVen do you need help with the requested changes? Please let us know if you need help! 😉

**Comment by hennevogel** [comment]
I guess this is not going anywhere. @StavyVen please open another PR if you are up for working on this. thanks!

**Pull request closed without merging**
