### PR TITLE
Add permission to access admin/shedule by cfp #1432

### LINKED ISSUE #1432: Permission to access admin/schedules by cfp
Currently only users with `organizer` role can manage admin/schedules as specified in https://github.com/openSUSE/osem/blob/master/app/models/ability.rb#L160 .

Users with role `cfp` handles the events in a conference so giving them access to schedules as well is something that could be considered .

### PR DESCRIPTION
**Pull request by nasia-sam**
Modified app/models so users with cfp role have the ability to access to admin/schedules as well . Resolves #1432

### CODE REVIEW

**Comment by BelieveC** [comment]
@nasia-sam  Nice Work! Please fix typo `admiin` in the commit title. Commit description in the commit message would help others a great deal when checking commits later. Please go through commit guidelines [here](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md#commits) and add description containing how you are fixing issue and end it with a reference to issue you are closing like [here](https://help.github.com/articles/closing-issues-via-commit-messages/) :wink:

**Comment by nikhilgupta1211** [comment]
@nasia-sam  you also have to change https://github.com/openSUSE/osem/blob/master/spec/features/ability_spec.rb#L164 to
`expect(current_path).to eq(admin_conference_schedules_path(conference2.short_title))`   **:)**

**Comment by differentreality** [comment]
@nasia-sam if you reference the issue you are closing in your commit message (preferably at the end) it will automatically close the issue when this PR is merged :)

**Comment by differentreality** [comment]
@nasia-sam so please amend your commit message, then we can merge this :)

**Comment by differentreality** [comment]
Thanks @nasia-sam ! :tada:

**Pull request merged**
