### PR TITLE
Allow admins to manually confirm users

### PR DESCRIPTION
**Pull request by nishanthvijayan**
Solves #1061 

manual-confirm

### CODE REVIEW

**Comment by hennevogel** [comment]
Please turn this into a [Bootstrap-Switch-Checkbox](https://github.com/openSUSE/osem/wiki/Bootstrap-Switch-Checkbox)

**Comment by nishanthvijayan** [comment]
Why a checkbox?Do we need to allow unconfirming as well?

**Comment by hennevogel** [comment]
Because this is how we handle boolean things in the UI.

**Comment by Chaz6** [comment]
Thank you for working on this.

**Pull request closed without merging**
