### PR TITLE
Better description to avoid sign up failures

### PR DESCRIPTION
**Pull request by chashmeetsingh**

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
@differentreality

**Comment by hennevogel** [comment]
Please attach screenshots of the visual change

**Comment by chashmeetsingh** [comment]
I did't find any change using hint, but when I used placeholder instead of hint it did show up place holder tag in the input boxes . relaxing placeholder by hint was suggested by @differentreality @hennevogel

**Comment by hennevogel** [comment]
If there is no visual change what is this PR about then? :-)

**Comment by chashmeetsingh** [comment]
there is a visual change while using placeholder @differentreality asked me to change it to hint instead 
Should I change it to placeholder?
@hennevogel

**Comment by differentreality** [comment]
No, you need to make hint work :)

**Comment by chashmeetsingh** [comment]
ok :)

**Comment by chashmeetsingh** [comment]
@differentreality my main aim was to specify that the length of the password should be specified
I googled ways to provide hints and found 2 ways

- using JS add value then on focus remove value
Problem with this is we will no be able to display the text it will show .........

- using placeholders as I earlier demonstrated 

Following output with placeholder
screen shot 2016-03-03 at 10 44 49 pm

**Comment by differentreality** [comment]
@chashmeetsingh Your PR does not make any change. We cannot review a PR that makes no change!

**Comment by hennevogel** [comment]
@chashmeetsingh You want to read up on [HTML5 form elements](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#forms) especially the [minlength](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#the-maxlength-and-minlength-attributes) attribute and [formtastic hints/labels](http://www.rubydoc.info/github/justinfrench/formtastic)

**Comment by chashmeetsingh** [comment]
@hennevogel @differentreality can u try this

`.container
  .row
    .col-md-6.col-md-offset-3
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            Sign Up
        .panel-body
          = semantic_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
            = f.input :username, input_html: { required: true, placeholder: 'Eg. john_doe' }
            = f.input :email, input_html: { required: true, placeholder: 'Eg. abc@example.com' }
            = f.input :name, input_html: { required: true, placeholder: 'Eg. John Doe' }
            = f.input :password, input_html: { required: true, placeholder: 'Min. 6 characters' }
            = f.input :password_confirmation, input_html: { required: true, placeholder: 'Same as above' }
            %p.text-right
              = f.action :submit, as: :button, label: 'Sign Up', button_html: { class: 'btn btn-success' }

          = render partial: 'devise/shared/openid'
          = render partial: 'devise/shared/help'`

**Pull request closed without merging**
