### PR TITLE
Add description to xml. fixes #1435

### LINKED ISSUE #1435: Missing description field in schedule xml
The app giggity complains about the xml returned by our osem installation. 

The problem is that the xml doesn't have a description field.

### PR DESCRIPTION
**Pull request by davidsf**
Add field description with the content of abstract to schedule show xml.  Fix #1435

### CODE REVIEW

**Comment by ChrisBr** [comment]
Why is abstract not enough?

**Comment by differentreality** [comment]
@davidsf can you please provide some feedback (there is more discussion in the issue) so that we can close this?
Also please reference the issue in your PR description.

**Comment by differentreality** [comment]
@davidsf ping

**Comment by davidsf** [comment]
@differentreality Adding the description field with the abstract information works well  for us. Giggity works with both fields, so I think the content of this PR should be merged.

Thanks

**Comment by Ana06** [comment]
@davidsf I think it would be useful to add a description in the commit message explaining that we add this field to make this work with Giggity

**Comment by differentreality** [comment]
OK let's get this in!

**Pull request merged**
