### PR TITLE
change escape_html: false to true

### PR DESCRIPTION
**Pull request by agrim123**
Previously due to https://github.com/openSUSE/osem/blob/master/app/helpers/application_helper.rb#L298 
was causing below problem
old
whereas expected is new

### CODE REVIEW

**Comment by ChrisBr** [comment]
@agrim123 the html: false was by intention to fix XSS 
https://github.com/openSUSE/osem/pull/1243

**Comment by agrim123** [comment]
@ChrisBr I am trying to fix it and the problem that i have stated :smile:

**Comment by agrim123** [comment]
@ChrisBr Tthe previous issue is now resolved .
Now we need to pass markdown to the markdown function

**Comment by ChrisBr** [comment]
Makes sense!
Thanks @agrim123

**Pull request merged**
