### PR TITLE
Admin users datatable bug fixed

### PR DESCRIPTION
**Pull request by rishabhs95**
Adding bootstrap table-responsive in datatable.
Issue #842 fixed.

### CODE REVIEW

**Comment by ChrisBr** [comment]
Hey @rishabhs95,

PR #839 already contains feaa61d, so please remove it from this PR (I commented in #839).
Furthermore, it seems like db32854 and f3924f6 are containing the same changes? So please remove either db32854 or f3924f6. And can you also get rid of  b034d04 and [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) instead?

**Comment by ChrisBr** [comment]
Otherwise, good work :+1:

**Comment by rishabhs95** [comment]
okay, i will do that

**Comment by rishabhs95** [comment]
improved PR opened at #845.

**Comment by ChrisBr** [comment]
@rishabhs95 so #845 supersedes this one and we can close it, right?

**Comment by rishabhs95** [comment]
yes

**Pull request closed without merging**
