### PR TITLE
Fixed 1195 Made charts responsive for mobile devices.

### PR DESCRIPTION
**Pull request by nikhilgupta1211**
#1195 
The charts were not working properly on mobile devices they were continuosly growing on scrolling.

### CODE REVIEW

**Comment by Ana06** [comment]
@nikhilgupta1211 can you please add a screenshot? :wink:

**Comment by nikhilgupta1211** [comment]
Yeah sure 😊	

image 
this screenshot is after the fix.

@Ana06  to reproduce this error please open this link on your mobile 

http://demo.osem.io/admin/conferences

or you can also reproduce this error by changing devices in the chrome toggle device toolbar .

**Comment by nikhilgupta1211** [comment]
@Ana06 i did some changes in this please have look at them . Thank you :)

**Comment by differentreality** [comment]
What's the status on this?

**Comment by Ana06** [comment]
@differentreality 

> What's the status on this?

I didn't have time to review it, fell free to review it. If not I'll do it ASAP. :wink:

**Comment by differentreality** [comment]
@Ana06

**Comment by svbeon** [comment]
+1

**Comment by differentreality** [comment]
This is an issue for a lot of people, the fix seems to be working, so in lack of any better ideas, I'll merge it.
Thanks @nikhilgupta1211 :+1:

**Pull request merged**
