### PR TITLE
ProposalController#create refactor

### LINKED ISSUE #597: Refactor
https://github.com/openSUSE/osem/blob/master/app/controllers/proposal_controller.rb#L24

ProposalController#create to be more simple and understandable. 
Tests should stay green, code should be simplified

### PR DESCRIPTION
**Pull request by chocoelho**
Resolves #597 by using method extraction.

### CODE REVIEW

**Comment by hennevogel** [comment]
What's the value of extracting this code into methods if those methods are only used once?

**Comment by chocoelho** [comment]
It was a way to simplify the create method, user creation makes more sense to be extracted rather than proposal submission. User creation has more chances to be reused than proposal submission. Maybe moving it to UsersController will be better.

**Comment by chocoelho** [comment]
I think user creation should be used as `before_action` only when create from proposal is called.

**Comment by hennevogel** [comment]
You should cross bridges when we you reach them, not before :-) It's a common mistake to program for the 'future' while making the 'present' unpleasant.  

Once you're in need of using the code behind `create_user_if_not_signed_in` or `proposal_submission` twice (some argue 3 times) you can start to think about moving this out.
If you don't have the need, the only thing you do by moving this to methods, is making it harder to understand/read. People who maintain this code (a.k.a. reading it in 2+ years) will have to jump around in the file just to find out what `proposal_submission` *actually* means.

Another thing you should learn about is where things belong to. The only thing that belongs to helpers is code that supports views. Before filters don't.

**Comment by hennevogel** [comment]
I'm closing this, please don't let this discourage you. Keep up the good work! :v:

**Pull request closed without merging**
