### PR TITLE
Fix no method error in Admin::Events#index

### LINKED ISSUE #1411: No method error in Admin::Events#index
When you try to download XLS file from Admin::Events#index you get error as follows: 
Error: `undefined method 'reopen' for "streamed":String`

screenshot from 2017-03-27 00-05-23

Ref: [Link](https://github.com/straydogstudio/axlsx_rails/issues/18#issuecomment-132234648)

### PR DESCRIPTION
**Pull request by BelieveC**
Resolve error 'undefined method reopen for streamed:String' by updating gem 'axlsx_rails' from 0.2.0 to 0.5.0 with resolving dependencies of gem 'axlsx_rails' to required versions.

Closes #1411

### CODE REVIEW

**Comment by differentreality** [comment]
But this introduces the hakiri issue again, which was fixed in https://github.com/openSUSE/osem/pull/1323

**Comment by BelieveC** [comment]
@differentreality 

I went through dependencies for ` axlsx_rails -v '0.5.0'  `, those are as follows:

- ` axlsx_rails -v '0.5.0' ` depends on `axlsx (2.0.1)` 
- `axlsx (2.0.1)` depends on `rubyzip (~> 1.0.0)`

So was not able to find a complete fix to both Hakiri and XLS file download issues. Will continue trying to fix it and will keep you updated with status.

**Comment by differentreality** [comment]
Yes, but it is best that we make this clear in the description, so that everybody understands when seeing this, that you are reverting the commit that fixed the hakiri issue before, and that you are proposing to keep the hakiri issue in order to make the xls export work. 
So the description of the PR should have that explanation and should also be referencing the PR and commit  you are reverting.

**Comment by BelieveC** [comment]
@differentreality, I will make the changes in the description :+1:

**Comment by BelieveC** [comment]
Done :+1:

**Comment by differentreality** [comment]
I am not sure what is done. Also please push new commits to your pull requests.

**Comment by BelieveC** [comment]
@differentreality 
I have updated gem `axlsx_rails` from `0.2.0` to `0.5.0` using command `bundle update axlsx_rails`. It updates gem `axlsx_rails` & resolves its dependencies.

**Comment by differentreality** [comment]
I am confused, the description says that by updating the axlsx_rails gem, we resolve the issue. However you are also changing the version of other gems, is that necessary?
And with axlsx 0.5.0 version, do we still have to downgrade rubyzip which causes the hakiri issue?

**Comment by BelieveC** [comment]
I tried manually updating axlsx_rails gem by making following changes in Gemfile.lock to avoid updating other gems via `bundle update axlsx_rails` 
- `axlsx_rails (0.2.0)` to `axlsx_rails(0.5.0)` 
- added its dependency `actionpack (>= 3.1)`
But it didn't work. 

> you are also changing the version of other gems, is that necessary

`bundler` automatically resolved versions of other gems when I did `bundle update axlsx_rails`.

> And with axlsx 0.5.0 version, do we still have to downgrade rubyzip which causes the hakiri issue?

Even I tried manually resolving `rubyzip` to `1.2.1` even then XLS export issue persist. 

Looking forward to suggestion.

**Comment by BelieveC** [comment]
@differentreality Any changes or suggestions?

**Comment by BelieveC** [comment]
@differentreality 
I discussed above issue with @lagartoflojo on IRC, we reached following conclusion:
- We have two options: 
    1. Don't fix the XLS problem until the new version of `axlsx` version is released.
    2. Upgrade `axlsx` and downgrade `rubyzip` at the same time

- Probably `axlsx(2.1.0)` update will resolve `rubyzip` Vulnerability. Ref: [link](https://github.com/randym/axlsx/issues/513)
- We can wait till our next release for `axlsx` update to resolve `axlsx_rails` version. Till then we can close this PR.

**Pull request closed without merging**
