### PR TITLE
Booth states can be changed in bulk

### LINKED ISSUE #2574: Automate bulk actions for evaluation and acceptance process
**My Approach**
1. Admin visits the booths#index.
2. A select option that includes all the available options for a booth request will be available, admin can select any option.
3. Checkboxes before every booth request in booths#index. Admin can select any number of checkboxes.
4. Submit button at the bottom. Admin will press the submit button.
5. At the controller, the status of the selected booths (point 3) will be changed according to the selected option(point 2) if it is allowed. Otherwise, an error flash message will be shown at booths#index.

### PR DESCRIPTION
**Pull request by rahul2240**
closes #2574 

**Checklist**

- [x] I have read the [Contribution & Best practices Guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md).
- [x] My branch is up-to-date with the upstream `master` branch.
- [x] The tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works(if appropriate).
- [x] I have added necessary documentation (if appropriate).

**workflow**
1. Admin visit the booths#index page.
2. Select any booth from the select column.
3. Go to top select bar and select the available options. 
4. Click on the option and all the booths with the same state as that of selected booth will be changed to new state.

**Changing state together**

ezgif com-video-to-gif

### CODE REVIEW

**Comment by differentreality** [comment]
While we can keep this for changing multiple booths' state at once, the idea behind this feature is not so much to select 50 booths and change their state (that becomes rather impractical in real situations), but to be able to change all booths in state 'to_accept' into state 'accepted' (same for rejection).

**Comment by rahul2240** [comment]
@differentreality I have updated the code and please see if it is what we need.
ezgif com-video-to-gif

**Comment by differentreality** [comment]
I'm confused :/ 

I'd expect that we are able to change all booths with X state into Z state.

**Comment by rahul2240** [comment]
@differentreality, with this PR, we are able to change the booth state of all booths that are in state 'X' to state 'Y'. Isn't this what we want?

**Comment by differentreality** [comment]
@rahul2240 admin/booths#index have radio buttons, not checkboxes, we can only select 1 booth at a time, shouldn't we be able to select multiple booths?

**Comment by rahul2240** [comment]
@differentreality, we had checkboxes but then we discussed this

> While we can keep this for changing multiple booths' state at once, the idea behind this feature is not so much to select 50 booths and change their state (that becomes rather impractical in real situations), but to be able to change all booths in state 'to_accept' into state 'accepted' (same for rejection).

then I added radio buttons because I wanted admin to select any 1 booth with state 'X', and the dropdown on top is already showing "change same state stands to other state". Now admin can change all 'X' state to 'Y' state.

**Comment by hennevogel** [comment]
Closing this for lack of activity...

**Pull request closed without merging**
