### PR TITLE
Remove unused call_for_paper model and controller files

### PR DESCRIPTION
**Pull request by nishanthvijayan**
call_for_paper model and controller are not being currently used.

### CODE REVIEW

**Comment by ChrisBr** [comment]
Really???

**Comment by nishanthvijayan** [comment]
call_for_paper renamed to cfp in #728

**Comment by ChrisBr** [comment]
Hmm, @differentreality can you please review, maybe there was a reason to not remove the cfp model and controller ...

**Comment by differentreality** [comment]
Can't recall, or figure out, if there was indeed a reason, or if it has been done by mistake.

**Pull request merged**
