### PR TITLE
Add flash type error.Rewrite controllers to use common flash style wi…

### PR DESCRIPTION
**Pull request by nishanthvijayan**
As recommended in #804 , added flash_type :error and rewrote all redirect_to statements to use the same style

### CODE REVIEW

**Comment by sonalkr132** [comment]
@nishanthvijayan Can we [change](https://github.com/openSUSE/osem/pull/858/files#diff-d438f64a44599197d7a8f71b0a65e039R18) [them](https://github.com/openSUSE/osem/pull/858/files#diff-1403510ba5f98202f033151a8787c089R28) [all](https://github.com/openSUSE/osem/search?p=1&q=flash+error) please?

**Comment by nishanthvijayan** [comment]
The remaining instances of flash[:notice / :alert / :error] are being used with render and redirect_back_or_to.
They don't seem to support passing flash as argument.

**Comment by nishanthvijayan** [comment]
I've also left out 2 other cases where replacing flash seemed impractical/impossible.See [here](https://github.com/openSUSE/osem/blob/af168f0f557a551022c361cc5aa9a039bec94c2d/app/controllers/admin/roles_controller.rb#L51) and [here](https://github.com/openSUSE/osem/blob/056df982b822e0a41b6937bd3e0c412574d4b481/app/controllers/admin/questions_controller.rb#L68)

**Comment by sonalkr132** [comment]
> They don't seem to support passing flash as argument.

[Interesting](https://rails.lighthouseapp.com/projects/8994/tickets/4911-patch-add-notice-alert-and-flash-as-options-to-render)  :astonished:

**Comment by nishanthvijayan** [comment]
@differentreality  I've made the changes like you asked.

**Comment by ChrisBr** [comment]
@nishanthvijayan sorry for the delay, I'll review today!

**Comment by ChrisBr** [comment]
@nishanthvijayan good work :+1: 

However, I recognized that we use different flash types for the same actions/failures. For instance, sometimes we use ``:error`` and sometimes ``:alert`` when updating / saving goes wrong! It would be nice if this would also be consistent.

From my POV: ``:notice`` for successfully saving / creating is fine. For failure while saving / updating I'd go with an ``alert`` type. @hennevogel @differentreality what do you think?

**Comment by differentreality** [comment]
I would go for error on failure to update/save. And I am  OK with some alert types we have for cancan exception, or when the user is not signed in.

**Comment by ChrisBr** [comment]
@nishanthvijayan so please change all update/save failures to ``:error``! Thanks!

**Comment by nishanthvijayan** [comment]
@ChrisBr  Done.

**Comment by ChrisBr** [comment]
@nishanthvijayan Awesome! Thanks a lot :+1:

**Pull request merged**
