### PR TITLE
Users changes

### PR DESCRIPTION
**Pull request by differentreality**
Mostly styling changes in admin/users#show

Fixes https://github.com/openSUSE/osem/issues/667

### CODE REVIEW

**Comment by ChrisBr** [comment]
@differentreality cool :)
Do you have screenshots?

**Comment by differentreality** [comment]
Ah yes, sorry forgot to add them!

screenshot-osem - chromium

screenshot-osem - chromium-1

**Comment by ChrisBr** [comment]
LGTM :+1:

**Comment by Doctor-Who** [comment]
Great works thanks !

**Pull request merged**
