### PR TITLE
fixed ticket turnover bug

### LINKED ISSUE #1918: Ticket turnover currency is different from price currency
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**

The admin/tickets#index page shows turnover amount in dollars irrespective of the price_currency
new-ticket-bug

**Expected correct behavior:**

For each ticket the turnover currency should be same as price currency
**Steps to reproduce:**

1) For changing currency there should be a single ticket
2) Change its currency other than USD
3) Price currency is different from turnover amount currency

### PR DESCRIPTION
**Pull request by ViditChitkara**
closes #1918

**Checklist**

- [x] I have read the [Contribution & Best practices Guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md).
- [X] My branch is up-to-date with the upstream `master` branch.
- [X] The tests pass locally with my changes.
- [X] I have added tests that prove my fix is effective or that my feature works(if appropriate).
- [X] I have added necessary documentation (if appropriate).

new-ticket-bug-solved

### CODE REVIEW

**Comment by differentreality** [comment]
@ViditChitkara please fix the failures so that we can review the PR :-)

Happy New Year!

**Comment by ViditChitkara** [comment]
@differentreality thankyou and a happy new year to you too!!
Sure, I'll fix the changes.

**Comment by ViditChitkara** [comment]
@differentreality The Travis failures are due to sponsorship_level_spec. Don't know how this is happening even though there are no changes made related to sponsorship levels. Could you please have a look

**Comment by ViditChitkara** [comment]
There are certain flaky tests occurring and are not at related to my changes! @differentreality @bear454 please have a look!

**Pull request merged**
