### PR TITLE
Add open graph meta data to conference#show

### PR DESCRIPTION
**Pull request by sherrimitchell**
#1178  Add Open Graph Meta Data to conference#show

### CODE REVIEW

**Comment by sherrimitchell** [comment]
conference_show_meta_data

**Comment by sherrimitchell** [comment]
Facebook posting example for conference#show.
conference_show_facebook

**Comment by differentreality** [comment]
@sherrimitchell can you please rebase this PR? Thanks :-)

**Comment by ChrisBr** [comment]
@sherrimitchell could you please rebase? Would love to merge this!

**Comment by ChrisBr** [comment]
superseded by #1231

**Comment by ChrisBr** [comment]
superseded by #1231

**Pull request closed without merging**
