### PR TITLE
Fix indentation issue in notification dropdown layout

### PR DESCRIPTION
**Pull request by siddhantbajaj**
screenshot from 2017-03-31 02 30 03
There is an issue in notification drop down menu (I have highlighted it with black colour).

### CODE REVIEW

**Comment by differentreality** [comment]
Then do we really need this `if`:
https://github.com/openSUSE/osem/blame/master/app/views/layouts/_navigation.html.haml#L32

**Comment by siddhantbajaj** [comment]
No actually I don't think this if condition has any significance here. So we can actually remove this.

**Comment by Ana06** [comment]
@differentreality 
> Then do we really need this if:
https://github.com/openSUSE/osem/blame/master/app/views/layouts/_navigation.html.haml#L32

That depends on if we want to show the notification panel when there are not notifications, right?

**Comment by siddhantbajaj** [comment]
> That depends on if we want to show the notification panel when there are not notifications, right?

@Ana06 Yes, but right now this if condition evaluates to true every time even if there are no notifications (unread_notifications will return empty array). So I think we should change this if condition if we don't want notification panel when there are no notifications to something like this:
`unless unread_notifications(current_user).empty?`

**Comment by Ana06** [comment]
@siddhantbajaj 

> @Ana06 Yes, but right now this if condition evaluates to true every time even if there are no notifications (unread_notifications will return empty array). So I think we should change this if condition if we don't want notification panel when there are no notifications to something like this:
unless unread_notifications(current_user).empty?

Yes, or just always show the panel with 0 notifications when it is empty. Both solutions are fine for me.

**Comment by Ana06** [comment]
@siddhantbajaj @differentreality what do we want to do then?

**Comment by siddhantbajaj** [comment]
> just always show the panel with 0 notifications when it is empty

@Ana06 I think this is much better fix because there might be a case when there are no unread notifications but user wants to see the previous seen notifications. So I think we should always show the notification panel.

**Comment by differentreality** [comment]
I think this looks good. Notifications drop down shows always, and it at least has the 'show all comments' link, right?

If so, I'd say let's prepare it for merging.

**Comment by differentreality** [comment]
:+1:

**Pull request merged**
