### PR TITLE
prefilled users arrival time with dates of the conference#623

### PR DESCRIPTION
**Pull request by Shriyanshagro**
Now , arrival/departure time while registering for conference will be prefilled with start_date and end_date of conference.

### CODE REVIEW

**Comment by differentreality** [comment]
I don't think we should prefill those values. Each attendee should indicate this, if he/she wants to. It is a very personal choice when someone will arrive to and leave from a conference. 
I think we are just going to end up with false information if we prefill these fields.

**Comment by Shriyanshagro** [comment]
But on [issue](https://github.com/openSUSE/osem/issues/623) . It was discussed , that there should be prefilled arrival/departure date , so that the people too lazy to fill this in don't get frustrated by it.

**Comment by differentreality** [comment]
That might be the title but it is not what is being discussed in the issue. Also discussion does not equal decision. In any case, I was merely stating my opinion. There are more people whose opinion weighs in, let's see what they think.

**Comment by Shriyanshagro** [comment]
Okay , than lets wait for others to put in their opinion. If you would ask me, I would suggest let it be prefilled with dates (+/-)1 days with actual dates of conference.

**Comment by ChrisBr** [comment]
What about leaving it empty by default but when I click on the datetimepicker the start / end date is preselected?

**Comment by Shriyanshagro** [comment]
@ChrisBr  ,do you mean that, dates would get preselected , only when we click on datetimepicker for first time??

**Comment by ChrisBr** [comment]
@Shriyanshagro for instance

**Comment by hennevogel** [comment]
Yes this is what pre-select means :-)

**Comment by Shriyanshagro** [comment]
So , is this the final idea to implement ??

**Comment by hennevogel** [comment]
Yes

**Comment by hennevogel** [comment]
Please make one pull request or this is not reviewable

**Comment by Shriyanshagro** [comment]
okay . Will create new Pr  with new idea been discussed here.

**Pull request closed without merging**
