### PR TITLE
replaced if-else with case-when

### PR DESCRIPTION
**Pull request by v0dro**
Solves #599

### CODE REVIEW

**Comment by hennevogel** [comment]
You don't catch the case where progress is 90 or 80. 
```ruby
irb(main):021:0> target_progress_color(90)
=> "red"
irb(main):022:0> target_progress_color(80)
=> "red"
```

**Comment by v0dro** [comment]
I just took the `if-else` above as a reference.

Should the code be something like this? :

``` ruby

case
  when progress >= 90 then 'green'
  when progress < 90 && progress >= 80 then 'orange'
  else 'red'
end
```

**Comment by v0dro** [comment]
@hennevogel updated :)

**Comment by hennevogel** [comment]
Looks good to me! :bouquet:

**Pull request merged**
