### PR TITLE
Add open graph metadata to event#show

### PR DESCRIPTION
**Pull request by sherrimitchell**
#1177 Add Open Graph Meta Data to event#show

### CODE REVIEW

**Comment by ChrisBr** [comment]
Please add some screenshots!

**Comment by sherrimitchell** [comment]
event_comments

**Comment by ChrisBr** [comment]
@sherrimitchell I'm not sure if you understand what this issue is about?

1) You changed `` app/views/proposal/show.html.haml `` but you attached a screenshot of ``/app/views/admin/events/index.html.haml`` 
2) I would like to see an image of the embedded events show page e.g. in facebook. 

This is what I understand the issues is about...
Do you need more help / information?

**Comment by sherrimitchell** [comment]
@ChrisBr I mistakenly attached the wrong image to my comment. So I can understand your confusion. 
* I have attached the correct screenshot. [event#show](http://imgur.com/VhS9uju)
* The issue states that the meta data should be embedded in the page to support social media card embedding. So the requested tags were added to the page, and I included the screen shots to show the meta data tags and values in the header follow the OEmbed format.
* Since Facebook uses Open Graph objects, I tested the implementation using the Facebook dev environment and ngrok to verify that the meta tag object data was being posted correctly.
* If you would prefer that I also include a screenshot of the embedded events#show page being displayed in Facebook as an example, I can provide.

Thanks!

**Comment by ChrisBr** [comment]
@sherrimitchell good :+1: 

Yes, please provide a screenshot of facebook as well, thanks :smile:

**Comment by sherrimitchell** [comment]
@ChrisBr I have attached a copy of the event#show page data in Facebook
event_show_facebook

**Comment by differentreality** [comment]
@sherrimitchell can you please rebase?

@hennevogel @ChrisBr is that all we need for this PR/issue?

**Comment by ChrisBr** [comment]
@sherrimitchell please rebase!

**Comment by ChrisBr** [comment]
superseded by #1231

**Pull request closed without merging**
