### PR TITLE
Fix send emails because missing event program relation.

### LINKED ISSUE #835: email is not sent when event is accepted
I have configured an custom email when the event is accepted.

But when an event is accepted, the email isn't sent.

### PR DESCRIPTION
**Pull request by davidsf**
Fix send emails because missing event program relation. fix #835

### CODE REVIEW

**Comment by sonalkr132** [comment]
hey @davidsf It would be great if you could add tests `mailbot.rb` and `email_settings.rb` have least coverage.

**Comment by differentreality** [comment]
@davidsf do you plan on adding tests?

**Comment by differentreality** [comment]
Ping @davidsf

**Comment by davidsf** [comment]
Sorry for the delay. Currently I don't have too much time so for now I can't add the test to this PR. Maybe in a near future, I hope :)

**Comment by ChrisBr** [comment]
Okay, thanks @davidsf anyway ... merging!

**Pull request merged**
