### PR TITLE
Migrate to fontawesome 6

### PR DESCRIPTION
**Pull request by hellcp**
**Checklist**

- [x] I have read the [Contribution & Best practices Guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md).
- [x] My branch is up-to-date with the upstream `master` branch.
- [ ] The tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works(if appropriate).
- [ ] I have added necessary documentation (if appropriate).

**Short description of what this resolves/which [issues](https://github.com/openSUSE/osem/issues) does this fix?:**

- I was trying to make a change where I needed a bit more modern set of fonts, this should allow me to contribute other stuff in the future
- I haven't actually tested this particularly well, so that's still ahead of me

**Changes proposed in this pull request:**

- Replace every other icon font with fa6

### CODE REVIEW

**Comment by hellcp** [comment]
Codacy can't ever be happy it seems

**Comment by hennevogel** [comment]
> Codacy can't ever be happy it seems

It's like you 😜

**Review by hennevogel — APPROVED** [review]

**Comment by hennevogel** [comment]
Awesome, did you do all this manually or do you have a script?

I didn't check all the icons, let's deploy and see who complains 😉

**Comment by hellcp** [comment]
Most of it was manual, some of it was sed

**Pull request merged**
