### PR TITLE
Update several gems

### PR DESCRIPTION
**Pull request by ChrisBr**
To fix CVE's reported by Hakiri.io

### CODE REVIEW

**Comment by ChrisBr** [comment]
@hennevogel please review!

**Comment by ChrisBr** [comment]
@differentreality please review!

**Comment by differentreality** [comment]
@ChrisBr :+1:  plz rebase

**Comment by ChrisBr** [comment]
@differentreality done, dropped fb776193198a8619d6dead452502c696518be157 (we don't need protected attributes anymore...)

**Comment by ChrisBr** [comment]
JFYI: the hakiri error is already in master so I'm not going to fix it in this PR!

**Comment by differentreality** [comment]
Yeap, I guess I shouldn't have used permit! in strong_params PR.

We can include the fix somewhere else, perhaps I can put it in my grooming PR (#721)

I think you are good to go! :) :+1:

**Comment by differentreality** [comment]
Does this PR close https://github.com/openSUSE/osem/pull/732 too?

**Comment by ChrisBr** [comment]
@differentreality Hm, no because I only upgraded the rails to the latest upgrade in 4.1. We should upgrade in the future to 4.2 but it isn't urgent anymore because all security issues are fixed now!

**Pull request merged**
