### PR TITLE
To enable navbar collapse on clicking outside the navbar

### PR DESCRIPTION
**Pull request by itaditya**
To enable navbar collapse on clicking outside the navbar .
To make it mergeable I have to make some more commits . Please guide me if there is a problem with that . ;)

### CODE REVIEW

**Comment by differentreality** [comment]
Hey :-) 

Could you write in more detail which problem you are trying to solve?

**Comment by itaditya** [comment]
Thanks for replying : ) . In mobile screen , when the navbar hamburger(menu) btn is clicked , it expands , but it only caollapse when the user clicks on that button only. So I have made this improvement in which it also collapse when the user clicks anywher on the screen . Thus I think it imroves UX . (Maybe you have seen this behaviour for modals in which on clicking outside the modal it dissapears .)

**Comment by differentreality** [comment]
@itaditya thank you for working on this! Can you please split the 2 issues in different PRs? You also have some changes that are irrelevant to what you are trying to fix.

**Comment by itaditya** [comment]
Ok I'll do that
;)

**Comment by itaditya** [comment]
Hello, I found that this issue was a duplicate of #1096 , and so I have sent a PR on that properly , please review it .

**Pull request closed without merging**
