### PR TITLE
show users per question

### PR DESCRIPTION
**Pull request by differentreality**
https://github.com/openSUSE/osem/issues/645

### CODE REVIEW

**Comment by ChrisBr** [comment]
LGTM
But I though #645 was related to the xls export function?

**Comment by differentreality** [comment]
@ChrisBr Hans said:

"@differentreality Both, either combined in one list or separate doesnt matter, as long as we get the data out."

#645 is quite vague.

**Comment by hcderaad** [comment]
#645 was triggered because of the export function not working. I still very much would like to have that working but for now a possibility of having a way to at least tell who answered which question and the answer would help. But again, a flat CSV export would be enough for me as long as it's realised very soon. Sorry to put the pressure on, but we really need this info for oSC15 now.

**Comment by hcderaad** [comment]
Sorry to put so much pressure on this, but we're coming to a serious standstill in the organization of oSC15 because of this issue. Please update me on the progress.

**Comment by ChrisBr** [comment]
@differentreality LGTM
Thanks for fixing this so quickly!

**Comment by hennevogel** [comment]
Let's merge this, then I deploy

**Comment by differentreality** [comment]
@hcderaad 
Hey, we are not your employees and it is certaintly not our fault you posted this issue 1 week before the conference :)
No offense but this is way too short of a notice for community volunteers to help you.
Your attitude is spoiling all the fun of us (volunteers).. And a politer attitude would go a long way!

**Pull request merged**
