### PR TITLE
Fix gradient in schedule page in Firefox

### LINKED ISSUE #748: UI discrepancy in schedule page
I have created 2 events with 1 hr and 2 hr each and schedule page shows some discrepancy.

URL: http://confoo.in/conference/4th_way_workshop_2016/schedule

Screenshot:
screenshot from 2016-01-11 12-17-31

### PR DESCRIPTION
**Pull request by davidsf**
Fix gradient in schedule page in Firefox. fix #748

### CODE REVIEW

**Comment by sonalkr132** [comment]
hey @davidsf just push you commit again. Check out [my build](https://travis-ci.org/sonalkr132/osem).

**Comment by differentreality** [comment]
Can we have screenshots please?

**Comment by davidsf** [comment]
captura de pantalla de 2016-02-21 11-25-06

**Comment by differentreality** [comment]
That looks as it should. @hennevogel  wanna take a look?

**Pull request merged**
