### PR TITLE
Add in the database migration step to the CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by kormoc**
Thanks @genehack for the original diff

### CODE REVIEW

**Comment by differentreality** [comment]
Hey @kormoc, I just wanted to make a note that the `db:migrate` is **not** necessary for the initial installation. When you run `vagrant up` it loads automatically the db schema. So running `db:migrate` after that, will do nothing.

You only have to run the `db:migrate `command, if you are running vagrant, you `git pull` changes that include a new migration, and you want to apply this single migration, without re-running `vagrant up`. 

Feel free to reach out and let us know if you ran into a different situation.

**Comment by genehack** [comment]
I added that line because when I pulled the *SeaGL fork* and tried to stand it up locally following the instructions, I had to manually do the migration. 

It's possible that issue had already been fixed in the automation code in the upstream.

**Comment by AEtherC0r3** [comment]
I will double check this issue

**Comment by hennevogel** [comment]
Here is your double check -> https://github.com/openSUSE/osem/blob/master/bootstrap.sh#L18

**Comment by kormoc** [comment]
Yes, generally this isn't needed, however when switching between branches/forks, it's often a required step to re-run the migration, so I felt that having it documented is at worst is a noop and at best will prevent weird issues from lack of migrations. Sometimes it's hard to know for sure that an error is due to a missing database migration.

**Pull request closed without merging**
