### PR TITLE
Fix Datepickers in Call for Content

### PR DESCRIPTION
**Pull request by Ana06**
Datapickers in Call for Events/Booths/Tracks were broken which made impossible to create them (as the date is required).

Those are not the only Datepickers broken and a similar solution should work for the rest as well.

Fixes https://github.com/openSUSE/osem/issues/2349

image

### CODE REVIEW

**Comment by Ana06** [comment]
I haven't managed to change the date in the datepickers by using Javascript. See issue at:

https://github.com/TrevorS/bootstrap3-datetimepicker-rails/issues/66

I also tried to use capybara-bootstrap-datepicker gem, but also didn't work. See my branch [datepickers-gem](https://github.com/openSUSE/osem/compare/master...Ana06:datepickers-gem?expand=1) and the issue https://github.com/akarzim/capybara-bootstrap-datepicker/issues/14

Because of that I have disabled the test. I even doubt if we need a feature test for this. The functionality was completely wrong and the test didn't fail anyway.

**Comment by Ana06** [comment]
I haven't managed to change the date in the datepickers by using Javascript. See issue at:

https://github.com/TrevorS/bootstrap3-datetimepicker-rails/issues/66

I also tried to use capybara-bootstrap-datepicker gem, but also didn't work. See my branch [datepickers-gem](https://github.com/openSUSE/osem/compare/master...Ana06:datepickers-gem?expand=1) and the issue https://github.com/akarzim/capybara-bootstrap-datepicker/issues/14

Anyway, it doesn't make sense to test this with a feature test as it is just testing that the controller actions work properly. Also, he functionality was completely wrong and the test didn't fail. So, I've replaced those feature test by controller tests.

**Comment by ehrenfeu** [comment]
Hi @Ana06,

for me disabling (removing) the `pickTime` from `osem-datepicker.js` worked well, i.e. something like this:

```diff
diff --git a/app/assets/javascripts/osem-datepickers.js b/app/assets/javascripts/osem-datepickers.js
index 598204ae..a682f3dc 100644
--- a/app/assets/javascripts/osem-datepickers.js
+++ b/app/assets/javascripts/osem-datepickers.js
@@ -53,7 +53,6 @@ $(function () {
    });
 
    $("#conference-start-datepicker").datetimepicker({
-       pickTime: false,
        useCurrent: false,
        format: "YYYY-MM-DD",
        // conference-start-day >= Current_date
```

Unfortunately I don't have the time right now to finish it up and do a PR, but maybe this still helps...?

Cheers,
Niko

**Comment by Ana06** [comment]
@ehrenfeu

> for me disabling (removing) the pickTime from osem-datepicker.js worked well, i.e. something like this:

 this is exactly the change I am introducing and there is a PR to do this in more places https://github.com/openSUSE/osem/pull/2391

The only "problem" with this PR was adapting the tests after the change.

**Pull request merged**
