### PR TITLE
Turbolinks updated to version 5

### LINKED ISSUE #1890: Update Turbolinks gem to version 5
We are currently using the [classic](https://github.com/turbolinks/turbolinks-classic) version, which is deprecated.
This will fix the before/after_filter and alias_method_chain deprecation warning that are shown on boot up

### PR DESCRIPTION
**Pull request by namangupta01**
closes #1890

### CODE REVIEW

**Comment by namangupta01** [comment]
@AEtherC0r3 Its done!

**Comment by namangupta01** [comment]
@AEtherC0r3 adding `//= require turbolinks` leads to failure of many test cases :(

**Comment by AEtherC0r3** [comment]
Then we need to fix them

**Comment by differentreality** [comment]
@namangupta01 do you need help to proceed with the necessary changes?

**Comment by namangupta01** [comment]
@differentreality yes please! I am not getting why these feature tests are failing.

**Comment by AEtherC0r3** [comment]
I haven't found an acceptable solution to the problem yet. Maybe we should only update the gem to get rid of the deprecation warnings and open a separate issue to enable it.
@differentreality what do you think?

**Comment by namangupta01** [comment]
@AEtherC0r3 Should i remove `//= require turbolinks` ?

**Comment by differentreality** [comment]
@namangupta01 can you check if all tests pass when you disable piwik?

https://github.com/openSUSE/osem/blob/master/app/views/layouts/application.html.haml#L47

**Comment by namangupta01** [comment]
@differentreality by disabling you mean removing this?

**Comment by hennevogel** [comment]
Updating turbolinks and preparing the app for turbolinks are two different things. @namangupta01 please more the `require` from application.js so we can get this merged.

**Comment by namangupta01** [comment]
@hennevogel I didn't get it. Do you want me to remove `require` from application.js ?

**Pull request closed without merging**
