### PR TITLE
added flash type messages

### PR DESCRIPTION
**Pull request by chashmeetsingh**

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
fixes #804 @differentreality

**Comment by sonalkr132** [comment]
@chashmeetsingh Why did you update the gemfile? If you want to update the gemfiles you can do it a separate PR. I don't think issue you are trying to fix requires update of Gemfile. It is also the most likely reason of your failing build.

**Comment by chashmeetsingh** [comment]
@sonalkr132 had to update because was repeatedly getting bundle install error for some gem . I did bundle update and everything fixed for me

**Comment by sonalkr132** [comment]
Please try to install master of osem. If you see any error, you can report it our issues page. 

If you do think it is something specific to your env, then you can ask questions at #osem (on freenode) and 	opensuse-web@opensuse.org, we will help you out.

**Comment by differentreality** [comment]
@chashmeetsingh something is wrong with your code, that is why tests cannot run.

Make sure your master is in sync with master on https://github.com/openSUSE/osem, then create a new branch, and then develop the feature you want to work on.

Please also do not include code that is irrelevant with the feature you are working on.

**Pull request closed without merging**
