### PR TITLE
Added flash_type error for code uniformity

### PR DESCRIPTION
**Pull request by AdiChat**
@differentreality I have updated a bunch of files and I request you to have a look and let me know if I am following the right path. Then I will tackle the rest of the files.
#804

### CODE REVIEW

**Comment by sonalkr132** [comment]
@AdiChat You really need to give some time to learning git https://git-scm.com/book/en/v2
If you don't like reading books, I am sure there are video tutorials out there too.

Your PR contains merge conflicts.

**Comment by AdiChat** [comment]
@sonalkr132  Yes I will start going through the book today itself.

**Comment by differentreality** [comment]
@AdiChat You need to
```
git checkout master
git pull origin master
git checkout AdiChat-flash-uniformity
git rebase origin/master
```

I am assuming that origin is the name of your remote.

After rebasing you will have conflicts, which you can see by
`git diff`

There will be instructions on your screen about how to proceed. Please rebase (and fix errors) and push again. You will have to do a forced push (`git push -f`).

You also need to read up on the structure of a rails application, and controller inheritance.

**Comment by AdiChat** [comment]
@differentreality I followed the instructions but forced push says everything is up to date and git diff provides no output which I assume means no conflict. So, I was unable to push again to avoid merge conflicts.
Nevertheless, thank you for stopping by and helping me out.
I will start going through git and structure of rails application and controller inheritance. I will complete this pull request and proceed with contributions in a couple of days after I have gained enough knowledge to do so.

**Comment by differentreality** [comment]
You might have already done git rebase before without fixing the conflicts?
I am closing this PR and you can open a new one when you are ready.

**Comment by AdiChat** [comment]
@differentreality I did git rebase before. Okay, I will open another pull request when I acquire the required knowledge.

**Pull request closed without merging**
