### PR TITLE
Groom proposal#show based on issue #731

### PR DESCRIPTION
**Pull request by alexdor**
Move speaker's avatar and bio to the sidebar and move proposal's information bellow the commercial.

### CODE REVIEW

**Comment by differentreality** [comment]
Can you please add a screenshot of your change?

**Comment by alexdor** [comment]
Yeah definitely, sorry for not including it in the first place.
screenshot from 2016-04-15 11 45 10

**Comment by hennevogel** [comment]
Like it

**Comment by differentreality** [comment]
With a commercial, however, the email is not shown properly.

screenshot-16

**Pull request merged**
