### PR TITLE
Update bootstrap-markdown to v2.10.0.Fixes markdown editors bug #811.

### LINKED ISSUE #811: Ticket description is not working
Steps to reproduce:
* Make a conference (say: goto)
* Go to new tickets page (url: http://localhost:3000/admin/conference/goto/tickets/new )
* Click in description text area, the markdown toolbar will appear and textarea goes out of focus.
* Keep clicking in it until the world doesn't make any sense :smile_cat: 
screenshot from 2016-03-03 17-10-24

Console says:
> Uncaught TypeError: this.$textarea.on(...).on(...).on is not a function

pointing to[ these lines](https://github.com/openSUSE/osem/blob/37697517df1a34a5d62773713307a93a0039d98a/vendor/assets/javascripts/bootstrap-markdown.js#L143-L147).

### PR DESCRIPTION
**Pull request by nishanthvijayan**
I've updated bootstrap-markdown to v2.10.0.All the markdown editors seem to working properly.
Fixes #811

### CODE REVIEW

**Comment by ChrisBr** [comment]
@hennevogel why don't we use the [gem](https://github.com/dannytatom/rails-bootstrap-markdown)?

**Comment by rishabhs95** [comment]
should i try working with the [gem](https://github.com/dannytatom/rails-bootstrap-markdown)?

**Comment by nishanthvijayan** [comment]
[rails-bootstrap-markdown](https://github.com/dannytatom/rails-bootstrap-markdown) seems to be using bootstrap-markdown v2.6.0 internally(see [here](https://github.com/dannytatom/rails-bootstrap-markdown/blob/master/app/assets/javascripts/bootstrap-markdown.js)).IMHO it doesn't seem to be actively maintained either.

**Comment by hennevogel** [comment]
Uh there is stuff in `vendor/assets`! Nice, I didn't know that. The correct solution is to use the rails assets gem. They have 2.10.0

**Pull request closed without merging**
