### PR TITLE
Dont show emails or real names

### LINKED ISSUE #1884: Personal information leak when editing proposals
### Problem:

Proposal submitters has access to personal data of (probably?) all the OSEM registered users. 

This is not acceptable and probably could be violating data privacy laws.

Verified in master branch at b9712209

### Expected behaviour:

3rd persons personal information should not be exposed to non-admin users.

### Steps to reproduce:

1. register at OSEM
2. submits a proposal
3. go to edit your submited proposal at, say, http://localhost:9292/conferences/MyConf/program/proposals/2/edit
4. edit the Speakers field
5. field displays a list of another users to select your co-speakers
6. this list exposes information for any other registered users: name username and email.

### Mitigation

You can do a quick fix with this patch:

```
diff --git a/app/views/proposals/_proposal_form.html.haml b/app/views/proposals/_proposal_form.html.haml
index 4b66240c..71bea2eb 100644
--- a/app/views/proposals/_proposal_form.html.haml
+++ b/app/views/proposals/_proposal_form.html.haml
@@ -4,7 +4,7 @@
 
     = f.input :subtitle, as: :string
 
-    = speaker_selector_input f
+    -# = speaker_selector_input f
 
     = track_selector_input f
```

At the cost of losing the feature of adding other speakers by the submitter.

### PR DESCRIPTION
**Pull request by captn3m0**
**Checklist**

- [x] I have read the [Contribution & Best practices Guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md).
- [x] My branch is up-to-date with the upstream `master` branch.
- [ ] The tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works(if appropriate).
- [ ] I have added necessary documentation (if appropriate).

**Short description of what this resolves/which [issues](https://github.com/openSUSE/osem/issues) does this fix?:**

- Fixes #1884 

**Changes proposed in this pull request:**

- Removes ~real names and~ email addresses from speaker select lists
- Trims down the list to just participants in the current conference

### CODE REVIEW

**Comment by captn3m0** [comment]
@Ana06 Thanks for the quick review. I decided to stick only with usernames because the profile page calls out the username field as "how others users see you". I'll change it to "Name (username)".

There are some test failures that I missed. Will fix them soon.

PS: This is live at https://osem.hillhacks.in

**Comment by Ana06** [comment]
@captn3m0 

> @Ana06 Thanks for the quick review. I decided to stick only with usernames because the profile page calls out the username field as "how others users see you". I'll change it to "Name (username)".
> 
> There are some test failures that I missed. Will fix them soon.

great! :wink: 

> PS: This is live at https://osem.hillhacks.in

cool! :tada: maybe you want to add it to https://github.com/openSUSE/osem/wiki/Conferences-using-OSEM :wink:

**Comment by captn3m0** [comment]
@Ana06 Test failures are because the `speaker_ids` field doesn't get auto-populated anymore on the proposal edit page.

I tried with `select(organizer.id, from: 'event[speaker_ids][]')` to select it, but couldn't get it working.

**Comment by Ana06** [comment]
@captn3m0 

> the speaker_ids field doesn't get auto-populated anymore on the proposal edit page.

What do you exactly mean? :thinking:

**Comment by captn3m0** [comment]
This is how the proposal edit page looks now:

image

And this is how it looks on master:

image

Tested a bit more, realized it is because since the new code only shows: "registered users for this conference" in the potential speaker list, it skips out on the current user as well since registration is not part of the test.

I can either:

1. Force register the user for the test, but this might make the proposal edit page frustrating for users since you don't see your name in the speaker list till you register (which you might miss)
2. Add current user as an exception to the speaker lits always.

**Comment by captn3m0** [comment]
@Ana06 Any help on the above?

**Comment by hennevogel** [comment]
Sorry but I think I close this now, this seems very stale. Feel free to send the same changes again if you're ready to work on it! Thank you anyway :bouquet:

**Pull request closed without merging**
