### PR TITLE
Update rubocop to 0.49.1

### PR DESCRIPTION
**Pull request by lagartoflojo**
I ran `rubocop --auto-gen-config` to re-generate `rubocop_todo.yml`... I guess that's the way to go?

### CODE REVIEW

**Comment by differentreality** [comment]
That's the way to go! Let's get it in after the conflicts resolution.

**Comment by differentreality** [comment]
What's different when we resolve offenses prior to generating the todo file?

**Comment by Ana06** [comment]
@differentreality 

> What's different when we resolve offenses prior to generating the todo file?

because when you regenerate the todo file there shouldn't be offenses. If they are something is wrong.

**Comment by differentreality** [comment]
Ah you mean so that all offenses are excluded in the newly generated todo file? That makes sense. Of course we would still have to fix the offenses afterwards.

**Comment by lagartoflojo** [comment]
Closed in favor of #1591

**Pull request closed without merging**
