### PR TITLE
Add a readme file for translation

### PR DESCRIPTION
**Pull request by differentreality**
#887

### CODE REVIEW

**Comment by ChrisBr** [comment]
@differentreality the text itself LGTM! However, if you don't name your file ``.md`` Markdown won't work! I'd suggest ``TRANSLATION.md```. Furthermore a link to this file from our Readme would be good

**Comment by ChrisBr** [comment]
@differentreality why is it WIP?

**Comment by differentreality** [comment]
Just a temporary commit until we are ready to go :-)

**Comment by hennevogel** [comment]
Are we there yet? :-)

**Pull request merged**
