### PR TITLE
Fix email notifications

### PR DESCRIPTION
**Pull request by hennevogel**

### CODE REVIEW

**Comment by differentreality** [comment]
Letter opener still doesn't seem to work for me.
Jobs show 1 job (probably comming from the Mailbot.delay in controller, eg. https://github.com/openSUSE/osem/blob/master/app/controllers/admin/conference_controller.rb#L88)

```
Starting job worker
Job Mailbot.conference_date_update_mail (id=1) RUNNING
Job Mailbot.conference_date_update_mail (id=1) COMPLETED after 0.1335
1 jobs processed at 4.4494 j/s, 0 failed
```

It works if we add **.delay!** when calling build_email
https://github.com/openSUSE/osem/blob/master/app/mailers/mailbot.rb#L43
Like this:
```
build_email(conference,
                  user.email,
                  conference.email_settings.conference_dates_updated_subject,
                  conference.email_settings.generate_email_on_conf_updates(conference, user, conference.email_settings.conference_dates_updated_body)).deliver!
```

It works nicely if we don't call the Mailbot's function from the controller but call Mailbot for every individual email.

```
# app/controllers/admin/conferences_controller.rb

# In def update
conference_date_update_mail(@conference) if send_mail_on_conf_update

# And add function
private

def conference_date_update_mail(conference)
  User.joins(:subscriptions).merge(conference.subscriptions).each do |user|
    Mailbot.delay.build_email(conference,
      user.email,
      conference.email_settings.conference_dates_updated_subject,
      conference.email_settings.generate_email_on_conf_updates(conference, user,    
conference.email_settings.conference_dates_updated_body))
  end
end
```

**Comment by differentreality** [comment]
We would still need to add `.each` in https://github.com/openSUSE/osem/blob/master/app/mailers/mailbot.rb#L39

**Comment by hennevogel** [comment]
I would propose we dont mix up letter opener and general email fixing

**Comment by sonalkr132** [comment]
@hennevogel As @differentreality  mentioned, we need to add `.each` to following [line](https://github.com/openSUSE/osem/blob/master/app/mailers/mailbot.rb#L39)(and other similar lines) even for general email fixing:
```Ruby
User.joins(:subscriptions).merge(conference.subscriptions) do |user|
```

**Comment by hennevogel** [comment]
@sonalkr132 done

**Comment by sonalkr132** [comment]
@hennevogel I tried it with smtp of hotmail and email was sent for just last user :anger: 
> It works if we add .deliver! when calling build_email
https://github.com/openSUSE/osem/blob/master/app/mailers/mailbot.rb#L43
Like this:

```Ruby
build_email(conference,
                  user.email,
                  conference.email_settings.conference_dates_updated_subject,
                  conference.email_settings.generate_email_on_conf_updates(conference, user, conference.email_settings.conference_dates_updated_body)).deliver!
```
I can confirm this :point_up_2: . I added `deliver!` to end of `build_email` and finally emails were sent to all the users in subscription list.

**Comment by differentreality** [comment]
Not sure how we can confirm (in development) if this is working properly, unless jobs:work show 2 jobs, or letter opener shows 2 emails.

**Comment by sonalkr132** [comment]
@differentreality Try following:
* `git fetch https://github.com/hennevogel/osem update_gems:update_gems`
* `git checkout update_gems`
* Add `deliver!` to end of [this](https://github.com/openSUSE/osem/blob/master/app/mailers/mailbot.rb#L43) line: `build_email(..).deliver!`
* `rails s`
* `rake jobs:work`
* Set up conference
     * enable notification on update of conference date
     * subscribe a couple of users to conference
     * update date of conference
* Go to: `http://localhost:3000/letter_opener` it will show you all the mails being delivered to subscribed users even if tabs for sent mails did not open on its own.

> if this is working properly, unless jobs:work show 2 jobs,

It won't show two job, we are calling `delay` once and all the mails are one job.

HTH! :smile:

**Comment by hennevogel** [comment]
@sonalkr132 @differentreality completey reworked it using ActiveJob. Please review again.

**Comment by differentreality** [comment]
I see the emails :smile:

**Comment by sonalkr132** [comment]
Can we please get rid of [delayed_job_active_record](https://github.com/openSUSE/osem/blob/master/Gemfile#L148) from our Gemfile then?

**Comment by hennevogel** [comment]
@sonalkr132 it's still used as the backend. ActiveJob is just a layer in between.

**Pull request merged**
