### PR TITLE
Fix broken export 

### LINKED ISSUE #2432: Event/track exports are broken.
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
Exporting the events/tracks through the admin dashboard is landing to errors.
pdf

**Steps to reproduce:**
Create new events or tracks through admin dashboard and click on export buttons to export all/confirmed events.

### PR DESCRIPTION
**Pull request by rahul2240**
Fixes #2432 

**Checklist**

- [x] I have read the [Contribution & Best practices Guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md).
- [x] My branch is up-to-date with the upstream `master` branch.
- [x] The tests pass locally with my changes.

**Before**
diff1

**After**
PDF
a

CSV
b

### CODE REVIEW

**Comment by differentreality** [comment]
Have you tried this with PDF export? It doesn't seem to work for me.

`undefined method `table' for #<Prawn::Document`

**Comment by rahul2240** [comment]
@differentreality I was getting the same error but after changing the gem, the error was fixed. I will look into it once again.

**Comment by rahul2240** [comment]
@differentreality I have again verified, it's working for me. Can you check if your Gemfile has 'prawn-rails' gem instead of 'prawn_rails' .

You must be getting this error 
diff1

which is because of "prawn_rails" gem, it is outdated.

**Comment by differentreality** [comment]
Right, thanks @rahul2240 :tada:

**Pull request merged**
