### PR TITLE
Updated vagrant box to official Leap release

### LINKED ISSUE #824: Switch Vagrant base box
We are currently using `webhippie/opensuse-13.2` as the base box for our vagrant file. We should switch to one of the *official* [openSUSE boxes](https://atlas.hashicorp.com/opensuse). I guess `opensuse/openSUSE-Tumbleweed-x86_64` is the best choice as we're only using the Vagrant box for development.

### PR DESCRIPTION
**Pull request by chocoelho**
Resolves #824

### CODE REVIEW

**Comment by ChrisBr** [comment]
I like it :+1: 
@hennevogel: @chocoelho is right, there is not official release of a tumbleweed box ... so I would say using leap is fine :+1:

**Comment by hennevogel** [comment]
We need to check what happens when when you update...

**Comment by chocoelho** [comment]
What kind of tests should I try to check this out?

**Comment by ChrisBr** [comment]
@hennevogel you mean when you already have 13.2 box and now it's a leap box stated in the Vagrant file? I assume you have to destroy and recreate your box ...

**Comment by hennevogel** [comment]
Yeah there is only box [versioning](https://www.vagrantup.com/docs/boxes/versioning.html) for your own boxes. I guess we simply have to tell people to re-create their boxes

**Comment by chocoelho** [comment]
I know this is already merged, but one option was to give users a choice: you can whether use webhippie's box or opensuse's one.

**Comment by ChrisBr** [comment]
@chocoelho how?

**Comment by chocoelho** [comment]
Like this(and also offer opensuse official with 13.2 if needed

```
default_box = "opensuse/openSUSE-42.1-x86_64"
if $stdin.isatty
  if Dir.glob(File.join(File.dirname("__FILE__"), '.vagrant/**/id')).empty?
    options = ["opensuse/openSUSE-42.1-x86_64", "webhippie/opensuse-13.2"]

    puts "Bases boxes available locally:"
    puts '------------------------------'
    system('vagrant', 'box', 'list')
    puts
    puts 'Base boxes we can provide you:'
    puts '------------------------------'
    options.each_with_index do |value, i|
      puts "[#{i + 1}] #{value}"
    end

    print "Which box to use [#{default_box}]: "
    choice = $stdin.gets.strip
    options.each_with_index do |option, i|
      if option == choice || choice.to_i == (i + 1)
        default_box = option
        puts default_box
        break
      end
    end
   end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


  config.vm.box = default_box

  case config.vm.box
  when "opensuse/openSUSE-42.1-x86_64"
    config.vm.box_url = "opensuse/openSUSE-42.1-x86_64"
  when "webhippie/opensuse-13.2"
    config.vm.box_url = "webhippie/opensuse-13.2"
  end

```

**Comment by chocoelho** [comment]
Though I'm not sure how it'll work for Windows machines, but it'll work on Linux/OS X machines...

**Comment by ChrisBr** [comment]
@chocoelho no, to much code / complicated for too less gain ...

**Comment by chocoelho** [comment]
Fine :) it was just a suggestion. Users should move to opensuse official
boxes and drop webhippie box.

On Mon, Mar 7, 2016 at 1:05 PM Christian Bruckmayer <
notifications@github.com> wrote:

> @chocoelho <https://github.com/chocoelho> no, to much code / complicated
> for too less gain ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openSUSE/osem/pull/825#issuecomment-193316675>.
>
-- 
Carlos Coêlho
https://pencillabs.com
Github: @chocoelho <https://github.com/chocoelho>

**Pull request merged**
