### PR TITLE
Replace add userby email textinput in admin/roles#show with searchabl…

### PR DESCRIPTION
**Pull request by nishanthvijayan**
I've replaced the 'add user by email' text input in admin/roles#show with a searchable combobox listing email ID's of all users.I believe this is more user friendly.I've used the asset gem of [bootstrap-select](https://github.com/silviomoreto/bootstrap-select) for this purpose.

select1

### CODE REVIEW

**Comment by ChrisBr** [comment]
@nishanthvijayan does it scale?

**Comment by nishanthvijayan** [comment]
I didn't test it with more than a few users.So I don't know.Since the plugin is popular I was hoping it would be scalable.How should I test if it scales?

**Comment by nishanthvijayan** [comment]
I'll try and fix the build problems as well.

**Comment by hennevogel** [comment]
User.pluck(:email) won't scale ever :-)

**Comment by nishanthvijayan** [comment]
I'm not sure if I follow.I thought .pluck was the fastest way if only one attribute needs to be fetched.

**Comment by hennevogel** [comment]
It is the fastest. That doesn't mean its fast when you have 50.000 users :-)

**Comment by nishanthvijayan** [comment]
Right :)  Is there any other way to go about this?I'm drawing a blank. :\

**Comment by hennevogel** [comment]
How about autocompletion? You input at least 4 characters and it starts to search for Users :-)

**Pull request closed without merging**
