### PR TITLE
Added validations in  Registration model

### PR DESCRIPTION
**Pull request by siddhantbajaj**
I think registration should not created after registration period end date. Therefore I have added a validation in registration model for the same.

### CODE REVIEW

**Comment by differentreality** [comment]
What about a conference without cfp when organizers will simply submit talks?

**Comment by siddhantbajaj** [comment]
@differentreality Yes you are right it, It won't be applicable then. I have removed that validation.

**Comment by siddhantbajaj** [comment]
@sayalilunkad I have made the changes. :+1:

**Comment by differentreality** [comment]
I have some doubts whether or not we should have this. Technically what you wrote is accurate. However an admin/organizer etc are authorized to perform certain actions, including :new and :create for Registration.
https://github.com/openSUSE/osem/blob/master/app/models/ability.rb#L147

If we add this, our codebase and our ability.rb file will not match in what they allow and what not. In my opinion we should not add this.

**Comment by siddhantbajaj** [comment]
@differentreality Yes maybe you are right but aren't we already doing this in our app like organiser/admin can also manage events.
https://github.com/openSUSE/osem/blob/master/app/models/ability.rb#L159
But still we have this validation:
https://github.com/openSUSE/osem/blob/master/app/models/event.rb#L31

**Comment by differentreality** [comment]
Yes, but we have an open PR to introduce the feature of events created by admin

**Comment by differentreality** [comment]
Part of what this PR is trying to accomplish is covered with the tests of #new action in https://github.com/openSUSE/osem/blob/master/spec/controllers/conference_registration_controller_spec.rb

I suggest we add tests for #create action.

**Pull request closed without merging**
