### PR TITLE
Improve overall performance on not_signed abilities

### PR DESCRIPTION
**Pull request by esparta**
**Checklist**

- [x] I have read the [Contribution & Best practices Guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md).
- [x] My branch is up-to-date with the upstream `master` branch.
- [x] The tests pass locally with my changes.
- [X] No need of new tests (IMO)
- [x] I have added necessary documentation (in commit).

Rails can infer the type and ids on Polymorphic models, so there's no need to declare them.

Also, the code was using `pluck` which force the query to be executed every single time the method is called.

**Before**

    osem_1      | 07:39:11 web.1    | Started GET "/" for 172.20.0.1 at 2019-07-1207:39:11 +0000
    osem_1      | 07:39:11 web.1    |    (0.3ms)  SELECT
    "conferences"."custom_domain" FROM "conferences" WHERE
    ("conferences"."custom_domain" IS NOT NULL) ORDER BY start_date DESC
    osem_1      | 07:39:11 web.1    | Processing by ConferencesController#index as HTML
    osem_1      | 07:39:11 web.1    |    (1.3ms)  SELECT "events"."id" FROM
    "events" WHERE "events"."state" = $ 1  [["state", "confirmed"]]
    osem_1      | 07:39:11 web.1    |   ↳ app/models/ability.rb:39:in `not_signed_in'
    osem_1      | 07:39:11 web.1    |   Rendering layouts/application.html.haml
    osem_1      | 07:39:11 web.1    |   Rendering conferences/index.html.haml within layouts/application

**After**

    osem_1      | 07:43:18 web.1    | Started GET "/" for 172.20.0.1 at 2019-07-1207:43:18 +0000
    osem_1      | 07:43:19 web.1    |    (0.2ms)  SELECT
    "conferences"."custom_domain" FROM "conferences" WHERE
    ("conferences"."custom_domain" IS NOT NULL) ORDER BY start_date DESC
    osem_1      | 07:43:19 web.1    | Processing by ConferencesController#index as HTML
    osem_1      | 07:43:19 web.1    |   Rendering layouts/application.html.haml
    osem_1      | 07:43:19 web.1    |   Rendering conferences/index.html.haml  within layouts/application

- Performance improvement on not signed users views. In aggregate would help to high traffic sites.

**Changes proposed in this pull request:**

- With this change (if accepted) the application will be NOT executing a query against Event model on every single page view/render on unsigned users (which usually is the gross of visitors) saving CPU, Network and Database resources.

### CODE REVIEW

**Comment by esparta** [comment]
The test suite looks like failing on an un-related issue (Selenium/Chrome crashing?), let me know if I can do something to fix it.

**Comment by hennevogel** [comment]
@esparta you can rebase, it's fixed. Sorry for the noise..

**Comment by esparta** [comment]
Rebased!
Now the test-suite is green! The PR is ready to review, @hennevogel

**Comment by hennevogel** [comment]
Thank you for your first contribution @esparta! :bouquet: Keep them coming :grin:

**Pull request merged**
