### PR TITLE
put translation javascript code in separate file

### PR DESCRIPTION
**Pull request by differentreality**
That should work and hide our key.
@hennevogel ?

https://github.com/openSUSE/osem/issues/573

### CODE REVIEW

**Comment by hennevogel** [comment]
This would mean you have to change code (*osem-translation.js*) to configure transifex. Bad idea

**Comment by differentreality** [comment]
@hennevogel do you have any other proposal at all to make the translation work?

**Comment by hennevogel** [comment]
How it is implemented now is the right way. We just have to make it work...

**Comment by hennevogel** [comment]
I don't get it. Have you tried this?

**Comment by hennevogel** [comment]
See #585 for a correct fix

**Pull request closed without merging**
