### PR TITLE
Markdown

### LINKED ISSUE #1090: Add Markdown for User Entered Text Formatting
Sooo, why can't we format our biographies?

How about being able to add some flavor to talk descriptions?

Sure, this is a new feature, but one that is pretty required.

Tips on where to implement if one of the core team would like someone else to give a shot?

### PR DESCRIPTION
**Pull request by Ana06**
Add markdown to events abstract and users biography.

Closes #1090 and #701

### CODE REVIEW

**Comment by Ana06** [comment]
I am not sure what I should with abstract and biography in serializers. 

In event serializer we currently use:

``` ruby
simple_format(object.abstract).gsub('\n', '')
```

While in conference serializer we just do:

``` ruby
event.abstract
```

**Comment by ChrisBr** [comment]
@Ana06 I would just go with ``event.abstract`` as ``simple_format`` doesn't really makes sense here as ``simple_format != markdown``
http://apidock.com/rails/ActionView/Helpers/TextHelper/simple_format

@hennevogel @differentreality  ^^

**Comment by differentreality** [comment]
Also solving #701  (Perhaps you can mention this in the initial comment too)

**Comment by ChrisBr** [comment]
@Ana06 please rebase!

**Comment by ChrisBr** [comment]
LGTM

**Pull request merged**
