### PR TITLE
Every campaign has an end.

### PR DESCRIPTION
**Pull request by bear454**
Drop ahoy, because it's more trouble than it's worth. This means dropping
visits, campaigns, targets.

Campaigns are better run to analytics, such as:
* https://matomo.org/docs/tracking-campaigns/
* https://matomo.org/docs/tracking-goals-web-analytics/
* https://support.google.com/analytics/answer/1012040?hl=en

### CODE REVIEW

**Comment by bear454** [comment]
Resolves #379, #1885, #2191.

**Comment by hennevogel** [comment]
Clap Clap

**Comment by hennevogel** [comment]
@openSUSE/osem-admins any last minute objections? :-)

**Comment by bear454** [comment]
Wait... found a problem with demo data...

**Comment by bear454** [comment]
... never mind; I was on the wrong branch. Full steam ahead!

**Comment by bear454** [comment]
@hennevogel: merge anytime you're ready :D

**Comment by bear454** [comment]
Deployed to https://lfnw.org

**Pull request merged**
