### PR TITLE
Downgrade holderjs to 2.9.1

### PR DESCRIPTION
**Pull request by sonalkr132**
Latest version avilable on rails-assets.org is 2.9.1

### CODE REVIEW

**Comment by sonalkr132** [comment]
> Net::HTTPServiceUnavailable: <h2>This website is under heavy load (queue
full)</h2><p>We're sorry, too many people are accessing this website at the same
time. We're working on this problem. Please try again later.</p>

Great! :anger:

**Comment by differentreality** [comment]
Where do you see that info about the version?

**Comment by sonalkr132** [comment]
@differentreality go to https://rails-assets.org/ and type `holderjs` in search box, it will show all the version available.

Sorry, I can't provide more direct link, they are using js.

**Comment by sonalkr132** [comment]
I think they provide option to rebuild the gem, and import gems which are not available. However they are having major traffic issue. I think we would be able to `bundle install` until they get it together :person_frowning:

**Comment by sonalkr132** [comment]
I scheduled `holderjs` for rebuild, and 2.9.3 is available now.
screenshot from 2016-03-24 23-03-05

We won't need this.

**Pull request closed without merging**
