### PR TITLE
Trying travis without sudo - should run in container

### PR DESCRIPTION
**Pull request by bear454**
Just want to see if things still work ;-)

### CODE REVIEW

**Comment by bear454** [comment]
Container build:

screenshot from 2017-10-12 09-43-18

VM build:

screenshot from 2017-10-12 09-45-00

**Comment by bear454** [comment]
So, we don't need to run in a Travis VM at this point, but it's _surprisingly_ faster to do so.

**Comment by hennevogel** [comment]
I guess because there are way more people hammering on the container infrastructure :-)

**Comment by bear454** [comment]
@hennevogel no, our test suite is just slow. I'm looking at approaches to get us < 5 minute runs.

**Pull request closed without merging**
