### PR TITLE
Update email_settings.rb

### PR DESCRIPTION
**Pull request by skriesch**
registration_body for #603

### CODE REVIEW

**Comment by differentreality** [comment]
@skriesch this on its own it is not going to change anything for your PR https://github.com/openSUSE/osem/pull/661

The test suit fails because you introduce a name in the factory which does not exist anywhere in our code.

You should add this change in your original PR (a new commit to that PR) so that the tests can, hopefully, run successfully, so that we can merge your PR all together!

Does this make sense to you?

**Comment by skriesch** [comment]
What is a PR? I need changes in different files, that the test can be successfully. How can I add all in one commit?

**Comment by ChrisBr** [comment]
@skriesch PR is the short form for Pull Request ;)

You don't necessary need to put everything into one commit, you need it in your other PR / branch
(https://github.com/openSUSE/osem/pull/661)

Here are some good sites to get more familiar with git:
http://rogerdudler.github.io/git-guide/
https://try.github.io/
http://firstaidgit.io/

**Comment by skriesch** [comment]
I can't add something remote:
ERROR: Permission to openSUSE/osem.git denied to skriesch.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

@hennevogel: I want to push my commits on my notebook.

**Comment by differentreality** [comment]
@skriesch you should push to your own remote branch that corresponds to the PR (in this case skriesch:patch-5), once you push your changes to your remote github branch, if you have a PR from that branch, the changes will automatically appear in the PR as well.

**Comment by ChrisBr** [comment]
@skriesch As @differentreality already stated out, you should push your changes to your fork! You don't have push permissions to this repository, that's the reason why you create a Pull request!

Maybe this article helps you: https://help.github.com/articles/fork-a-repo/

**Comment by differentreality** [comment]
@skriesch it has been a while this PR is open, do you think you will work on it to wrap it up?

**Comment by skriesch** [comment]
Sorry, that I answer so late. A colleague is ill until next year and another one has changed the team. My days are full with work overtime at the moment. Additional our tests at the distance teaching university are coming.  I had too little of time in the last months.

I tried to push the content of the local machine to github. I get a 403 error with permissions...
sarah@linux-p095:~/osem> git push upstream skriesch-patch-4
ksshaskpass(2956)/kdeui (Wallet): The kwalletd service has been disabled 
ksshaskpass(2956)/kdeui (Wallet): The kwalletd service has been disabled 
ksshaskpass(2956)/kdeui (Wallet): The kwalletd service has been disabled 
ksshaskpass(2956)/kdeui (Wallet): The kwalletd service has been disabled 
ksshaskpass(2956)/kdeui (Wallet): The kwalletd service has been disabled 
ksshaskpass(2956)/kdeui (Wallet): The kwalletd service has been disabled 
ksshaskpass(2959)/kdeui (Wallet): The kwalletd service has been disabled 
ksshaskpass(2959)/kdeui (Wallet): The kwalletd service has been disabled 
ksshaskpass(2959)/kdeui (Wallet): The kwalletd service has been disabled 
ksshaskpass(2959)/kdeui (Wallet): The kwalletd service has been disabled 
ksshaskpass(2959)/kdeui (Wallet): The kwalletd service has been disabled 
ksshaskpass(2959)/kdeui (Wallet): The kwalletd service has been disabled 
remote: Permission to openSUSE/osem.git denied to skriesch.
fatal: unable to access 'https://github.com/openSUSE/osem.git/': The requested URL returned error: 403

**Comment by differentreality** [comment]
@skriesch please see @ChrisBr comment above. 

You cannot push to opensuse/osem.git, you must push to your own remote repo, https://github.com/skriesch/osem, and your PR will be automatically updated.

**Comment by differentreality** [comment]
Any update on this?

**Comment by differentreality** [comment]
Closing due to inactivity

**Pull request closed without merging**
