### PR TITLE
Fix authorization of new and create in ConferenceRegistrationsController

### PR DESCRIPTION
**Pull request by sonalkr132**
Closes: #791
Change in proposal spec cause conference has to have valid registration period for successful redirect to registration after confirm proposal.

### CODE REVIEW

**Comment by hennevogel** [comment]
Phew. I don't understand your description. Please elaborate

**Comment by sonalkr132** [comment]
@hennevogel Proposal confirmation gets redirected to new registration page. We need conference to be open for registration for the redirect.

We won't need it, after we have solved #802

**Comment by hennevogel** [comment]
Do we want to allow this? 

1. Someone unregistered submits a Talk to our conference
2. We allow registration until next Friday
3. Someone unregistered confirms his event on Monday

@differentreality @ChrisBr opinions?

**Comment by differentreality** [comment]
That workflow is currently possible. The thing is that if a speaker confirms, that means the speaker is going to attend the conference. It could make sense that the speaker is able to register.

It could, however, mean that people registered after the registration period closes, don't get to have some things that are time-sensitive, ie. badges that had to be printed on a certain date right after registration period closed. 
Of course the discussion is only about confirmed speakers, and you would expect that organizers would provision for their speakers separately.

But that is not related to this particular PR now, is it? 
Unless we also want to integrate provision for confirmed speakers within this PR, it makes total sense not to redirect to a page where the user has no access. And the user should not have access to new registration page, unless registration period is open.

**Comment by hennevogel** [comment]
Well this workflow is what what this PR fixes. I think we should think about this whole cycle more. I'll record an issue

**Comment by hennevogel** [comment]
But let's merge this for now

**Pull request merged**
