### PR TITLE
Expose enable_starttls_auto & openssl_verify_mode.

### PR DESCRIPTION
**Pull request by laosb**
And align `ENV` calls to keep up with codes above.

### CODE REVIEW

**Comment by differentreality** [comment]
We should also be defining the variables,  so let's add them in https://github.com/openSUSE/osem/blob/master/dotenv.example

**Comment by differentreality** [comment]
We should also be defining the variables,  so let's add them in https://github.com/openSUSE/osem/blob/master/dotenv.example

**Comment by laosb** [comment]
@differentreality Thank you for your reminder. I've added it in my last commit.

**Comment by differentreality** [comment]
@laosb Nice :+1:  please squash that middle commit, so that we can merge this.

**Comment by laosb** [comment]
@differentreality Thank you for your review, and I've squashed these commits!

**Pull request merged**
