### PR TITLE
 make sure that the registed link is there but only accessible to admins

### PR DESCRIPTION
**Pull request by NeimadTL**
bugfix on index proposals/index so the registed link is only accessible to admins

### CODE REVIEW

**Comment by differentreality** [comment]
Why should the link only be available for admins? Not even conference organizers? What about proposal submitters?

**Comment by NeimadTL** [comment]
I thought the conference organizers were the admins of the conferences they've created.
So the rule should be : link available for admins `or` conference organizers `or` proposal submitters. Is that correct @differentreality ?

**Comment by NeimadTL** [comment]
`if event.require_registration && (current_user.is_admin || event.event_users.include?(current_user))`
@differentreality, can you tell me if this is better please ?

**Comment by differentreality** [comment]
The check should be based on the ability of the user, and not the user's role. 
So we should check if the user can access the controller#action the button takes us to.

To check the abilities of each user we use [CanCanCan](https://github.com/CanCanCommunity/cancancan) gem and in order to check a certain ability you have to use a syntax like this:
`can? :index, @proposal`
Please read the gem's manual for more details: https://github.com/CanCanCommunity/cancancan/wiki/Checking-Abilities

If you haven't already found it, there is information on the roles in our wiki: https://github.com/openSUSE/osem/wiki/Roles-and-Permissions

**Comment by hennevogel** [comment]
Sorry but I think I close this now, this seems very stale. Feel free to send the same changes again if you're ready to work on it! Thank you anyway :bouquet:

**Pull request closed without merging**
