### PR TITLE
Button Redirection

### PR DESCRIPTION
**Pull request by konstantinos-zarzavatsakis**
#1813 We redirected the button to direct you to track#new

### CODE REVIEW

**Comment by Ana06** [comment]
@konstantinos-zarzavatsakis do you need help to do the changes? If so, please ask! 😉

**Comment by bear454** [comment]
@konstantinos-zarzavatsakis I'd like to get this merged in... please update!

**Comment by Ana06** [comment]
@konstantinos-zarzavatsakis any update? If you don't have time to finish it or need help please let us now. 😄

**Comment by konstantinos-zarzavatsakis** [comment]
Hello,
I pushed this change during a workshop I attended with a team of others. I
could not keep attending the workshop though due to a heavy schedule so I
do not have the time nor the people with the needed knowledge around to do
what's requested. So can you help or can you do what's necessary to fix it?

Thanks, Konstantinos

Στις 5 Ιαν 2018 17:50, ο χρήστης "Ana María Martínez Gómez" <
notifications@github.com> έγραψε:

**Comment by Ana06** [comment]
@konstantinos-zarzavatsakis no problem. I'll close this, so someone else can work on it. Thanks for your reply. 😉

**Pull request closed without merging**
