### PR TITLE
Name attribute in email

### PR DESCRIPTION
**Pull request by theaverageguy**
Fixes https://github.com/openSUSE/osem/issues/818

### CODE REVIEW

**Comment by ChrisBr** [comment]
@theaverageguy have you tested it? Still wondering why it doesn't work with ``name`` ...

**Comment by hennevogel** [comment]
`username` is nowhere fetched in EmailSettings...

**Comment by Shriyanshagro** [comment]
[b9469f6 ](url)

**Comment by Shriyanshagro** [comment]
tried to solved the issue , check if it works
#https://github.com/Shriyanshagro/osem/commit/17e7f49100269d929e626701b502e9f3a11c35e1

**Comment by hennevogel** [comment]
@Shriyanshagro it doesn't. See you other comment :-)

**Pull request closed without merging**
