### PR TITLE
Add place autocomplete

### PR DESCRIPTION
**Pull request by Abhinand-p**
Existing:
Latitude and longitude values are entered. These values are inserted to the Venues database and the map is generated. The entry of latitude and longitude values is an overhead for the user. 

Modified:
The geocode package is installed. The text areas for latitude and longitude inputs are eliminated. Based on the address specified, latitude and longitude values are automatically generated and entered to the Venues database. The map is now displayed based on the computed values. User need not explicitly enter latitude and longitude values.

### CODE REVIEW

**Comment by Abhinand-p** [comment]
I have used geocoder package to determine latitude and longitude values based on the address. 
I am getting unsuccessful checks. It is required to install geocoder and make entry in Gemfile.

**Comment by Abhinand-p** [comment]
image
image
Active record entries:
image

**Comment by ChrisBr** [comment]
Please fix the failing tests!

**Comment by Abhinand-p** [comment]
@ChrisBr 
Geocoder has to  be installed at server side with an entry "gem 'geocoder'" in Gemfile. This will make checks successful.

**Comment by differentreality** [comment]
If a gem is needed, you need to introduce it in your pull request

**Comment by differentreality** [comment]
@Abhinand-p ping, are you working on this? Can you finish this in the next week or so?

**Comment by differentreality** [comment]
@Abhinand-p do you plan on working on this? We would like to get this in within next week, so will you have time to work on it these days?

**Comment by differentreality** [comment]
Closing due to inactivity and lack of response

**Pull request closed without merging**
