### PR TITLE
fixes abstract count not showing properly

### LINKED ISSUE #590: Abstract word counting does not seem to work
When entering abstract for talk on openSUSE conference 2015 the abstract words are not counted. Regardless of the content I see there "You have used 0 words. Abstracts must be between 0 and 250 words. "

The browser is chromium 40 and only extension is adblock, so no disabled scripting.

### PR DESCRIPTION
**Pull request by v0dro**
Fixes #590 

I've worked with jQuery events before but never seen anything like it, can someone please explain?

### CODE REVIEW

**Comment by differentreality** [comment]
While counting works, min and max are still not displayed properly. Did you notice it?

**Comment by ChrisBr** [comment]
@v0dro Any progress? Do you still work on this one?

**Comment by v0dro** [comment]
I'm on it. Didn't get time. Will send another commit in a few hours.

**Comment by ChrisBr** [comment]
@v0dro No problem, just wanted to know if this is still active!

**Comment by hennevogel** [comment]
Please reopen once you find the time

**Pull request closed without merging**
