### PR TITLE
Add Docker-Compose support

### PR DESCRIPTION
**Pull request by dronov**
Hello! 

I tried to pack OSEM rails app into docker container and run it in development environment using Docker-Compose tool. I moved ```tzinfo-data``` gem to Gemfile cause container had been broken without it (you can see the solution to except it at Dockerfile). Also I installed nokogiri by strange way, cause bundler had some problems and had not succeed in solving them. 

It would be great if someone will give me some feedback. :)
Thanks a lot.

### CODE REVIEW

**Comment by ChrisBr** [comment]
@kalabiyau that's your thing ;)

**Comment by dronov** [comment]
My thoughts was to built an app with docker for development purposes, so I decided to go the simple way and use sqlite. I am not sure that this is the most correct way, cause I have never used sqlite for development, and maybe I should setup mariadb container and use it in OSEM rails app. 

BTW, @ChrisBr showed this issue https://github.com/openSUSE/mentoring/issues/23
I haven't saw it before submitting this PR :\

**Comment by hennevogel** [comment]
We're already using Vagrant for development. Why don't you [integrate](https://www.vagrantup.com/docs/docker/basics.html) docker instead of doing it standalone? :-)

**Comment by hennevogel** [comment]
@dronov any news on this?

**Comment by dronov** [comment]
@hennevogel Hello! 
I made standalone Dockerfile cause is it the usual way run app. And yeah, I did not know that the Docker could be use as a integration.

Btw, there is a connected issue, so maybe is it ok to pack OSEM rails app into container?

**Comment by hennevogel** [comment]
*usual way* is kind of a weak argument when it comes to containers... I would definitely want to avoid to add another tool to the mix we need to maintain...

**Comment by dronov** [comment]
@hennevogel docker don't have a lot of problems with maintaning project's dependencies. All dependencies fixed in Dockerfile and the're similar at all environments using Docker.

Anyway, I understand you. And sorry if I make some problems, it was not polite. 
Could I take another issue to solve?

**Comment by ChrisBr** [comment]
@dronov yes, sure! Just go ahead, it's open source, we welcome every contribution :+1:

**Comment by ChrisBr** [comment]
@dronov @hennevogel what's the final conclusion of this PR?

**Comment by hennevogel** [comment]
That we either use docker-compose or Vagrant. Not both.

**Pull request closed without merging**
