### PR TITLE
Fix edit and schedule buttons on proposal show page

### LINKED ISSUE #859: Edit and schedule of proposal ends up in unauthorized access
Steps to reproduce:
* Submit a proposal to a conference (say: goto)
* Visit the show page of proposal (link: http://localhost:3000/conference/goto/program/proposal/1)
* Click on edit or schedule button on top right.

The page will redirect to home and flash will say: "You are not authorized to access this page."

Link of edit button is `edit_admin_conference_program_event_path` when it should be `edit_conference_program_proposal_path`. Schedule is most likely getting denied access due to incorrect authorization setup.

### PR DESCRIPTION
**Pull request by sonalkr132**
closes #859

### CODE REVIEW

**Comment by differentreality** [comment]
Do we got tests for that? :D

**Comment by sonalkr132** [comment]
@differentreality feature tests? We don't have think kind of feature[1] tests anywhere. I guess we can start now?

[1]: where we test whether clicking on a link goes to given path

**Comment by hennevogel** [comment]
Tests for views are overkill. Either this is part of some workflow we want to make sure is do-able or we don't test this...

**Comment by hennevogel** [comment]
I would merge this as is

**Comment by ChrisBr** [comment]
okay, merging ...

**Pull request merged**
