### PR TITLE
Update error message

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes duplicity in the flash messages

### CODE REVIEW

**Comment by differentreality** [comment]
A proper title and a short description would be very helpful to people seeing your PR.

**Comment by Ana06** [comment]
And you can make that the issue is closed automatically by adding it to the commit message:

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by chashmeetsingh** [comment]
Didn't know the proper format for a commit message so avoided that.

**Comment by Ana06** [comment]
We have recently added the Pull Requests workflow to the CONTRIBUTING guide: https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md#pull-requests-workflow :wink:

**Comment by differentreality** [comment]
Please make the rest of the requested changes, ie add a description of this PR in the first comment, I would also appreciate a more comprehensive commit message that actually gives me a hint about what this commit message is about.

**Comment by Ana06** [comment]
@chashmeetsingh from the [CONTRIBUTING guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md#pull-requests-workflow):

> Title _(the first line of the commit)_:
>  - Include a comprehensive title about what this PR is doing
>  - Referencing the issue number on the PR title is **not** giving any information about what this PR is about
>  - The title should be short (50 characters maximum). You can add more information in the description
> 
> Description:
>  - Add a couple of lines about what is the problem you are trying to solve and how you have addressed it
>  - Add bullet points about the new things you are introducing, if applicable
>  - Reference the issue: https://help.github.com/articles/closing-issues-via-commit-messages

So according to this your commit should look like:

```
Remove duplicate text in error message

Remove `Start date` from the error set in `conference#valid_date_range?` as it is already automatically added and consequently it is duplicated.

Fixes #1345 
```

Please change it so we can merge this PR :wink:

**Pull request merged**
