### PR TITLE
Allow selection of future dates on registration period page

### PR DESCRIPTION
**Pull request by sonalkr132**
close: #798

### CODE REVIEW

**Comment by sonalkr132** [comment]
Hey, can I get rid of first commit?

**Comment by ChrisBr** [comment]
@sonalkr132 I'd prefer to keep it

**Comment by ChrisBr** [comment]
@differentreality what do you think? I like the DRY...

**Comment by differentreality** [comment]
+1 @ChrisBr, keep both commits, we do 2 different things in each commit. And I like that the commit messages clearly show that @sonalkr132

**Comment by ChrisBr** [comment]
so merging...
Thanks @sonalkr132

**Pull request merged**
