### PR TITLE
Withdrawn events on conference dashboard

### LINKED ISSUE #463: Dashboard: Withdrawn Events
At the top bar information there should be the following:
- sadly the event X, Y and Z where withdrawn

### PR DESCRIPTION
**Pull request by chocoelho**
Resolves #463.

It adds an alert whenever events on a conference get withdrawn. 

Screenshot:
image

### CODE REVIEW

**Comment by chocoelho** [comment]
Oh, np @Ana06. It's just that I've tried this before(last year if I'm not mistaken) and it was being applied to the admin interface. I can add it to the user side as well, without problems, but with some adjustments, such as using event titles instead of a counter because it'll make more sense on the user side.

**Comment by differentreality** [comment]
I think dashboard means admin/conferences#show, otherwise it would say splashpage 

I would also like to mention that I don't particularly like the implementation with the alert. I was hoping  that you may have a better idea on how to show this @Ana06

**Comment by chocoelho** [comment]
It could be another section in the dashboard view. Another way to implement this, although it would involve the alert, is to track state changing and display only withdrawn events since last user login or something like that using https://github.com/continuum/espinita.

**Comment by Ana06** [comment]
@differentreality 

> I think dashboard means admin/conferences#show, otherwise it would say splashpage

ok, sorry for the confusion then 👍 

> I would also like to mention that I don't particularly like the implementation with the alert. I was hoping that you may have a better idea on how to show this @Ana06

🤔  Maybe another section on the top of the dashboard with the withdrawn events?

**Comment by chocoelho** [comment]
So, section approach? @Ana06 @differentreality

**Comment by chocoelho** [comment]
@Ana06 @differentreality would something like this be better?

image

**Comment by chocoelho** [comment]
Same idea but with more withdrawn events:

image

**Comment by Ana06** [comment]
@differentreality what do you think?

**Comment by differentreality** [comment]
I like the charts :)

What about we also add a relevant icon on the top of the page? (next to Registrations, Submissions,Hours)

**Comment by differentreality** [comment]
:+1: I like it :)  
How about you squash your commits?

**Comment by chocoelho** [comment]
@differentreality @Ana06 I just squashed my commits into 3

**Comment by differentreality** [comment]
Nice, thank you @chocoelho :+1:

**Pull request merged**
