### PR TITLE
Update navbar link for "one-organization" profile

### LINKED ISSUE #1651: Browsing is confusing with organization name on the top left navbar
When I am anywhere (eg proposals#index) I see the organization name on the top left corner of the navigation bar. That takes me to organizations#index. 

Usually on the top left we find the link to homepage. 

Also there is nothing I want to do in organizations#index (99% of the time at least).

The organization name could be the same as the app name (for the non hosted version of OSEM), as such I see the exact same thing, which is directing me to a totally different place every time. And that's confusing.

### PR DESCRIPTION
**Pull request by bear454**
When osem is run with only one organization, it should function roughly the same as it did without organizations; the state in either case is that osem is functionally hosting only one organization, and therefore organizational settings can be at the top-level.

Only If multiple organizations are present, e.g. in a 'hosted' setting, do we need handle the organizational scope.

So, for the top navigational bar, only show the organizational link if there is more than one organization; otherwise show the top-level site link.

Resolves #1651 

*screenshots from specs*

Before:
capybara-201405010001114928339693

After:
capybara-201405010001136080047312

### CODE REVIEW

**Comment by bear454** [comment]
@differentreality please review (and merge if approved) when you have time.

**Comment by differentreality** [comment]
I think the homepage link should be there (on the top left corner) in both/all cases
More details: https://github.com/openSUSE/osem/pull/1657

**Comment by bear454** [comment]
@differentreality please review again

**Comment by differentreality** [comment]
@bear454 personally I love that the root_path is there at all times. I don't particularly like that the displayed name changes (sometimes it is OSEM sometimes it is the conference's organization name).

I would suggest we show
OSEM_NAME || OSEM  (-> root_path) and Organization name (linking somewhere relevant) next to it.

screenshot from 2017-11-07 17-22-32

What do you/others think?

**Comment by bear454** [comment]
IMO, we don't have much control over this anyway; if we decide to impose a requirement to say "OSEM", anyone can reverse that in their fork... so we might as well create something sustainable, by using a sensible default with an easily configured option to override.

**Pull request closed without merging**
