### PR TITLE
Simplify our contributing guide

### PR DESCRIPTION
**Pull request by differentreality**
It seems that people find it difficult to read through such a big contributing guide, so I am suggesting we keep the absolutely necessary information in the contributing guide itself, and move the rest in the wiki.

What I think is absolutely necessary:
* How to run OSEM in development mode, ie vagrant instructions
* How to test the code (rspec and rubocop)
* General information
* Contact info
* Code of conduct info

I have already moved the parts in the wiki: https://github.com/openSUSE/osem/wiki

This would close https://github.com/openSUSE/osem/pull/1389

### CODE REVIEW

**Comment by lagartoflojo** [comment]
Makes sense to me.

**Comment by lagartoflojo** [comment]
Btw, GitHub has an "official" place to put the CoC: https://github.com/openSUSE/osem/community.
Maybe we can also extract that part and put it there?

**Comment by Ana06** [comment]
@differentreality @lagartoflojo I have been pointing people to the sections from the documentation you removed. Even if we are more flexible when merging PRs I don't think that the documentation about how to write proper commits messages and PRs hurts. :-1:

**Comment by lagartoflojo** [comment]
@Ana06 the documentation is still there: https://github.com/openSUSE/osem/wiki/Commit-Guidelines

**Pull request merged**
