### PR TITLE
Upgrade to Rails 5.0

### PR DESCRIPTION
**Pull request by shlok007**
Refer to issue #1087 

2596c501faa3e459dd8257f27d7b14d98b623e41 This commit updates the Gemfile with compatible version of gems for Rails 5.0

- Removed `quiet-assests` gem as it is now built inside `sprocket-rails`. 
Reference: https://github.com/rails/sprockets-rails/pull/355 

- Removed `activeuuid` as rails 5 has built in support for uuid primary keys.

- `rails_observers` supported version for rails 5 has not yet been released. However, https://github.com/rails/rails-observers/pull/39 makes it compatible with rails 5, so using a forked repository helps. 

- `awesome_nested_set` updated to version `3.1`

519a361 Committed after running `rails app:update` . The overwritten configurations had to be added manually so, kindly review this.
Approach taken from: http://pages.citebite.com/q5b3s6r9u4nyk

cdd2242 Generated new schema. 
Reference: https://hashrocket.com/blog/posts/how-to-upgrade-to-rails-5#4-generate-the-db-schema-rb-file-again

Note: This is an ongoing PR and contains incomplete changes.

### CODE REVIEW

**Comment by hennevogel** [comment]
If it's ongoing please open the PR once you're ready for us to pull :-)

**Comment by hennevogel** [comment]
Especially after your PR to rails_observers is merged because this won't go into OSEM before...

**Comment by ChrisBr** [comment]
So let's close this one till it is ready to merge?

Anyway, @shlok007 thanks for your contribution and I will look forward when it's ready to merge! Highly appreciated :+1:

**Comment by siaw23** [comment]
any update on this? @ChrisBr @hennevogel @shlok007

**Pull request closed without merging**
