### PR TITLE
#1040 Show email in public option

### PR DESCRIPTION
**Pull request by JewelSam**

### CODE REVIEW

**Comment by JewelSam** [comment]
#1040 
But I don't know how I should update email_public of all existent users to true value. Do you usually do it using rake task?

**Comment by ChrisBr** [comment]
@JewelSam Yes we do it via rake task. However, for a boolean value with a default it should set to true by default, shouldn't it?

**Comment by JewelSam** [comment]
@ChrisBr I was suprised too, but no. 
I created task.

**Comment by Ana06** [comment]
The problem is that for the object already created the default was `nil`, so this will only affect the new ones, that's why you need the task :wink:

**Comment by ChrisBr** [comment]
LGTM

**Pull request merged**
