### PR TITLE
Adding comments to events#index

### PR DESCRIPTION
**Pull request by sherrimitchell**
#1135 View Comments in Events List

event_comments

### CODE REVIEW

**Comment by differentreality** [comment]
@sherrimitchell can you please add a screenshot of your change in the PR?

**Comment by ChrisBr** [comment]
@sherrimitchell cool :+1: 

But we can improve your changes with some advanced Rails techniques :) With your changes, every time I access events#index we make several COUNT calls. Instead hitting the database all the time we could instead cache it. Rails already implements this :smile: 

From the rails documentation:
```
belongs_to :author, dependent: :destroy, counter_cache: true
```
http://guides.rubyonrails.org/association_basics.html#options-for-belongs-to

Of course you would need a migration to add the column for storing the hash. However, I think it's worth the effort. These adaptions don't make the code more complicated and improve the performance A LOT!

**Comment by ChrisBr** [comment]
@hennevogel you're on vacation!!!

**Comment by sherrimitchell** [comment]
@ChrisBr thanks for the feedback. I definitely want to make this more efficient. I will make the changes that you suggested and submit. 😄

**Comment by differentreality** [comment]
@sherrimitchell @ChrisBr what's the progress on this?

**Comment by ChrisBr** [comment]
Let's merge it and open an issue for making this more efficient!

**Pull request merged**
