### PR TITLE
Simplify adding commercials to conference and event

### PR DESCRIPTION
**Pull request by ChrisBr**
User only has to paste the commercial URL, no need to extract the id etc from the URL anymore :)

@differentreality @hennevogel please review!

### CODE REVIEW

**Comment by ChrisBr** [comment]
This PR is based on #736, as soon as we merge #736 I will rebase and we will get rid of the first commit ....

**Comment by hennevogel** [comment]
Screenshots please

**Comment by ChrisBr** [comment]
Default:


Success:


Error:

**Comment by differentreality** [comment]
@ChrisBr looks good, once the factory in failing tests is fixed.

**Comment by differentreality** [comment]
@ChrisBr ping

**Comment by ChrisBr** [comment]
@differentreality I'll have a look at it tonight :)

**Comment by differentreality** [comment]
:+1:

**Comment by ChrisBr** [comment]
Cool, after almost one year we finally merged it :)

**Pull request merged**
