### PR TITLE
Fix reference to non-existant route path in commercials_controller

### PR DESCRIPTION
**Pull request by nishanthvijayan**
The route edit_conference_proposal_path was removed in [this commit](https://github.com/openSUSE/osem/commit/444356fb)

### CODE REVIEW

**Comment by differentreality** [comment]
Should we perhaps add a test case for when the creation and update are not successful? @ChrisBr

**Comment by hennevogel** [comment]
Yes we should

**Comment by nishanthvijayan** [comment]
updated.

**Comment by differentreality** [comment]
I would also test that we are on the right path, which is precisely what we are changing in this PR.

**Comment by nishanthvijayan** [comment]
Done

**Comment by hennevogel** [comment]
Awesome, thanks @nishanthvijayan

**Pull request merged**
