### PR TITLE
Display correct quantity of tickets in admin views

### PR DESCRIPTION
**Pull request by rishabhs95**
This displays the correct quantity of purchased tickets after integration of online payment feature.
This will be rebased over #1108 after merge.

### CODE REVIEW

**Comment by rishabhs95** [comment]
I think these changes are okay @lagartoflojo?

**Comment by lagartoflojo** [comment]
What's the bug that you are solving here? Or is it a refactoring? If it's a bug, I think we also need a test case :) The test case should fail on master, but pass on this branch.

**Comment by rishabhs95** [comment]
Just a small change in admin's ticket purchases view. There are no major model/controller/feature changes that's why all tests are passing at the moment on the master branch.

**Comment by lagartoflojo** [comment]
@rishabhs95 I still don't get it - I see it's a small change, but is it a bug fix or a refactoring?

**Comment by differentreality** [comment]
Maybe I am missing sth with how we are now implementing tickets, but is it possible that we have more than one TicketPurchase for the same user and the same ticket?

**Comment by rishabhs95** [comment]
Yes, it can be possible for a user to have more than one ticket purchase for the same ticket and that's why we are showing the total ticket quantity here. I would say it as a minor bug fix.

**Comment by lagartoflojo** [comment]
If it's a small bug fix, then we need a test case as I said before...

>  If it's a bug, I think we also need a test case :) The test case should fail on master, but pass on this branch.

**Comment by rishabhs95** [comment]
As the change is not related to any controller or any model, rather I am just repairing a `view` change. Currently, we don't have much testing in the views that is why I haven't fixed/changed any test case.

**Comment by rishabhs95** [comment]
Yes, a user can have multiple ticket purchases as they can be paid with different times and needs to be linked with its respective payment. @differentreality

**Comment by differentreality** [comment]
We don't really want to introduce any more view tests btw...

I wonder if it would make more sense to add a new column on that table with the quantity though.

**Comment by rishabhs95** [comment]
Yes, we can add another column for the quantity... the quantity sticker looks nice though :)
What do you think/prefer?

**Comment by differentreality** [comment]
I prefer the column (which is also sortable btw). 
I find the sticker fancy and all, but perhaps for  another page, not the main page for tickets.

**Comment by rishabhs95** [comment]
Okay... Pushing the new changes :)

**Comment by differentreality** [comment]
:+1:

**Pull request merged**
