### PR TITLE
Adding notranslate classes to ease translation of dynamic text

### PR DESCRIPTION
**Pull request by camillem**
Hi,
In order to fix issue #908 I have added some .notranslate classes so that non translatable elements are seen as such by Transifex. 
It doesn't solve the problems of the translation of dates and pluralized items. 
I only changed a few files in order to give a concrete base for discussion on the subject: I'm waiting for your opinions to know how to proceed further.

Camille

### CODE REVIEW

**Comment by ChrisBr** [comment]
@differentreality ^^

**Comment by hennevogel** [comment]
Looks like the right solution to me. Please also document this in the TRANSLATION.md file

**Comment by hennevogel** [comment]
@camillem please also document this in the TRANSLATION.md file

**Comment by camillem** [comment]
@hennevogel I will. May be it could also be relevant to mention it in the docs for devs who create new haml files?

**Comment by hennevogel** [comment]
It's okay there...

**Pull request merged**
