### PR TITLE
Make the input fields in sign in look bootstrapy

### PR DESCRIPTION
**Pull request by svbeon**
Add class form control to inputs

Before, mobile:
img_20170715_143256

After, mobile:
img_20170715_143334

Before, Desktop:
img_20170715_143316

After, desktop:
img_20170715_143439

### CODE REVIEW

**Comment by differentreality** [comment]
@svbeon could you please add before/after screenshots?

**Comment by svbeon** [comment]
@differentreality sure thing, I'll just have to spin up a development copy that doesn't have all my colour changes that our main copy has

**Comment by svbeon** [comment]
@differentreality there we go

**Comment by differentreality** [comment]
@svbeon did you just add changes to css which weren't there initially?

**Comment by svbeon** [comment]
@differentreality yes I realized those had been added since the version we're running at freenode.live (1.0) and those didn't look like what I was intending to suggest with this PR

**Comment by differentreality** [comment]
I don't see any difference with, or without, the CSS code any more (while form-control class is there) in XS or MD viewport. So this looks good @svbeon :+1: 

:tada: Thanks for your contribution :tada: 

Let us know what you think of OSEM, and how it is working out for your conference!
FYI we also support openid (I noticed you don't have it enabled, and wanted to make sure it was out of choice). Feel free to swing by #osem too!

**Comment by svbeon** [comment]
@differentreality thanks, we might pop up with a summary of what we think later on, probably after this year's conference, maybe earlier.

We did choose to disable openid because of some bug we couldn't trace (none of us speaks Ruby) that signed in everyone that used Facebook sign in as admins, which wasn't exactly preferable 😅 (and well, beeing months behind schedule did make disabling it a better option than trying to debug)

**Comment by differentreality** [comment]
@svbeon  oh, that's weird. I'd happily investigate this for you, if you send me some server logs.

**Comment by svbeon** [comment]
@differentreality would be wonderful. shall see if we can fix some logs, we're in the middle of launch and don't want to mess anything up, so i'll try creating a dev copy for it

**Pull request merged**
