### PR TITLE
Fixed email overflow bug in tickets pdf

### LINKED ISSUE #1691: Email in ticket shows beyond the square outline
screenshot from 2017-09-12 09-52-35

### PR DESCRIPTION
**Pull request by ViditChitkara**
closes #1691

### CODE REVIEW

**Comment by differentreality** [comment]
This is working for me. @rishabhs95 do you want to review?

**Comment by rishabhs95** [comment]
Just had a look! This looks good! @differentreality 😀

**Comment by differentreality** [comment]
@ViditChitkara  I think changes related to byebug need to be removed, before we can merge this :)

Can you please prepare your PR for merging? Thanks!

**Comment by ViditChitkara** [comment]
@differentreality byebug_history is removed. Also, shouldn't we add byebug_history to .gitignore file??

**Comment by differentreality** [comment]
Thanks @ViditChitkara :+1: Merging :tada: 

(Not sure about byebug_history file)

**Comment by ViditChitkara** [comment]
@differentreality thanks for merging. Shall I open an issue with feedback label for byebug related changes, since they are for personal use only and should be added to gitignore?

**Pull request merged**
