### PR TITLE
Specs added ConferenceRegistrationsController#new

### PR DESCRIPTION
**Pull request by charliequinn**
Increased test coverage with addition of specs to cover :new method of ConferenceRegistrationsController

### CODE REVIEW

**Comment by charliequinn** [comment]
not sure how this has failed on TravisCI, it was passing on my machine and on my repo's Travis CI https://travis-ci.org/charliequinn/osem/builds/151665514 

Honest guv' :) any feedback would be much appreciated

**Comment by differentreality** [comment]
It's a false positive, I have restarted Travis. Let's see :)

**Comment by hennevogel** [comment]
@charliequinn awesome  :fireworks:  thank you for your contribution! :bouquet: Keep it up :grinning:

**Comment by charliequinn** [comment]
Thanks @hennevogel means a lot. 

This is my first contribution to open source and you guys have been so welcoming and on the ball with PRs - a perfect way to start! :relaxed:  Hope I can contribute more!

**Comment by hennevogel** [comment]
@charliequinn I hope so too. If you can't find anything let us know and we'll find something for you. Keep on hacking! :grinning:

**Pull request merged**
