### PR TITLE
Add currency CHF

### PR DESCRIPTION
**Pull request by tobru**
This PR solves #1697.

If I get it right this is the only place which needs an update to add a new currency.

### CODE REVIEW

**Comment by differentreality** [comment]
@tobru I've been thinking, while this temporarily solves your particular problem it is not a global solution, and the more people use OSEM, the more this might come up. We should fix this for everyone.

One solution I can think of would be to include all available currencies in that drop down (this can be done with `Money::Currency.all`), and use `selectize-rails` so that it is possible to start typing the currency while it searches through the options.
(We are already using `selectize-rails` for proposals#form to select speakers.)

Thoughts?

**Comment by tobru** [comment]
Of course you're right, this only solves my particular need for having CHF available. Having all currencies available would be the best case here. I'm not a Ruby developer, I'm just using OSEM for DevOpsDays Switzerland and try to solve our needs as good as possible. If someone of the OSEM team is able to add support for all currencies: go for it and close my PR.

**Comment by differentreality** [comment]
Yeap makes sense! Thanks for sending your changes, we appreciate it :)
I've updated the issue as well, so it should be picked up.

By the way, can we add your conference to our wiki? 
https://github.com/openSUSE/osem/wiki/Conferences-using-OSEM
Feel free to send us the link!

**Comment by tobru** [comment]
Will send you the link as soon as it's ready

**Pull request merged**
