### PR TITLE
Ticket_button added

### PR DESCRIPTION
**Pull request by alxPgns**
https://github.com/openSUSE/osem/issues/1705

Added a button in conference_registrations#show that links to physical_tickets#index

### CODE REVIEW

**Comment by differentreality** [comment]
Nice work @alxPgns :+1: 
Could you please add a screenshot of your change?

**Comment by differentreality** [comment]
@alxPgns ping

**Comment by bear454** [comment]
Screenshot:

screenshot from 2017-12-11 17-04-49

**Comment by differentreality** [comment]
Thanks to both :)

**Pull request merged**
